### ISSUE TITLE
GC observability and WeakRefs

### ISSUE THREAD

**Issue by littledan** [w3ctag/design-principles#100]
[WeakRefs](https://github.com/tc39/proposal-weakrefs) reached Stage 2 in TC39, with multi-browser support (at least Chrome and Firefox). Should the GC observability advice be updated?

The text in that still seems like a good best practice to me, even if browsers are taking on the risk of exactly the brittleness that the section expressed concern about.

**Comment by yoavweiss** [comment]
Just bumped into that section and noticed the advice seems out-of-date. We should update it to indicate the proposal is now at stage 2.

**Comment by dbaron** [comment]
I think this was probably resolved by #129 but I should read the text again to double-check.

**Comment by torgo** [comment]
We think this was resolved by https://github.com/w3ctag/design-principles/pull/129
