### ISSUE TITLE
GC considerations and user-visible changes in state

### ISSUE THREAD

**Issue by rakuco** [w3ctag/design-principles#102]
At the [Devices and Sensors WG F2F at TPAC](https://www.w3.org/wiki/DAS/Meetings/October_2018_F2F#Agenda), w3c/wake-lock#128 tracks the problem of locks that currently cannot be released depending on how they are created.

The issue boils down to the fact that fixing that potentially involves describing some actions that must be performed when a lock is garbage collected, but that would also trigger changes to user-visible state (a `WakeLock`s `active` member would change). We had a similar problem in w3c/sensors#372, but for sensors there's no changes in object state that is visible to users.

We're wondering if there's a guideline for this kind of issue.

**Comment by domenic** [comment]
Isn't https://w3ctag.github.io/design-principles/#js-gc the guidance?

**Comment by littledan** [comment]
I'm glad the design principles document that best practice. I agree that depending on GC should be avoided. However, I think that, given that [WeakRefs](https://github.com/tc39/proposal-weakrefs) is at has cross-browser consensus and is at Stage 2, we should revisit the strength of the guidance (see https://github.com/w3ctag/design-principles/issues/100). WeakRefs leave open a much bigger space for observation of GC than the linked issue. And this leak seems intolerably bad.

**Comment by torgo** [comment]
Discussed on breakout 30-march-2020 and we think this has been addressed already in the document.
