### ISSUE TITLE
Prefixing particularly dangerous operations with "unsafe"

### ISSUE THREAD

**Issue by annevk** [w3ctag/design-principles#104]
This seems like a good pattern to endorse.

**Comment by kenchris** [comment]
Do you have a list of example on operations on the platform today, which you think should have been prefixed?

**Comment by annevk** [comment]
Not really, assuming I caught https://github.com/WICG/web-locks/issues/52 and https://github.com/WebAssembly/content-security-policy/issues/15 on time.

**Comment by dbaron** [comment]
The fun part is writing down what it means to be unsafe so that people can tell whether the thing they're working on counts.

**Comment by dbaron** [comment]
So based on the issues [@annevk linked](https://github.com/w3ctag/design-principles/issues/104#issuecomment-433293837), the precedent for this is CSP.  And in [CSP2](https://www.w3.org/TR/CSP2/), the keywords that are unsafe are `unsafe-inline` and `unsafe-eval` as allowed script sources.  These are unsafe in the sense that they mean you lose a bunch of the protections against content injection vulnerabilities that CSP provides.  [CSP3](https://w3c.github.io/webappsec-csp/) adds `unsafe-hashes` and `unsafe-allow-redirects`.  The former is similar to the other CSP ones; I'm not that familiar with `unsafe-allow-redirects` but I think it's somewhat similar but maybe a different threat model?  The [WebAssembly issue @annevk linked](https://github.com/WebAssembly/content-security-policy/issues/15) seems pretty similar to the original CSP ones.

In the [Web Locks case @annevk linked](https://github.com/WICG/web-locks/issues/52), `steal` is about doing something that's unsafe in the sense of breaking the guarantees that the specification is providing to its other callers, who believe they've acquired exclusive access to the resource.

**Comment by dbaron** [comment]
So I think the common thread here is that these specs are about providing certain guarantees:  In CSP's case, protection against certain security vulnerabilities; in the case of Web Locks, about providing exclusive access to certain resources.  I think what makes these operations "unsafe" is that they break or reduce the guarantees that the specification itself offers.
