### ISSUE TITLE
More naming advice: avoid "brand" names

### ISSUE THREAD

**Issue by travisleithead** [w3ctag/design-principles#106]
The web will likely outlive the "branded" thing your API name is based on. Better to chose a name for the capability it offers, rather than a clever brand 'de jour'.

**Comment by kenchris** [comment]
We will still use names like Bluetooth because it depends on the tech. Maybe don't use brands/tech names unless its specifics are exposed in the API (which is sometimes the point, eg. USB, Bluetooth)

**Comment by annevk** [comment]
(Bluetooth is somewhat controversial for the reason @travisleithead mentions. It's platform-dependent and unclear if it'll outlast the web. I don't think it's been well articulated why breaking principles in such cases is okay.)

**Comment by cynthia** [comment]
There was a recent review that exposed a very specific subset/revision of Bluetooth, which I think probably would fall into the scope of this issue.
