### ISSUE TITLE
High level or low-level APIs?

### ISSUE THREAD

**Issue by travisleithead** [w3ctag/design-principles#117]
## Background

Was watching this [Kranky Geek video](https://www.youtube.com/watch?v=gV354kWh08o&feature=youtu.be&list=PL4_h-ulX5eNfaM0QM5r-PewWaY_zgLH7b&t=1226) (time index 20:00 - 30:00 mins) about WebRTC moving to potentially lower-level APIs with the majority of the "features" of the implementation of the WebRTC internals managed by Web Assembly (some native C app transpiled to WASM). This got me thinking about the general idea of porting native apps to the web using WASM and what it means for the design of Client Side APIs.

WASM programs must still run within the web sandbox--e.g., they are *not* granted special exception to access low-level OS/Driver functionality. From this POV, there is really nothing risky about this direction that web design might take. However, it begs the question of whether the web's current pattern of building relatively high-level APIs is the best approach.

The term "high level" must also be clarified. Over time, esp., with the adoption of the Extensible Web Manifesto, browser vendors have begun focusing on uncovering the "building blocks" that make other higher-level features work. Case-in-point, Web Components aim to explain how high-level markup languages work, enabling web applications to extend or create their own high-level markup languages for distribution on the web. The downside is that the code to power these experiences is not built-in to the browser, and must be downloaded by every client that visits the web site.

Is the approach to WebRTC as shown in the video just the natural evolution of the path we started down with the Extensible Web Manifesto, or is this a development that is beyond simply providing a new set of "low-level" APIs to explain RTC?

Common sense tells me that there should be a happy medium of API design that makes the most sense for the most developers.

This issue is opened to track the discussion around this topic and hopefully land on some recommendations we can provide via the design principles document for those designing APIs.

## Existing Discussion Questions

* If more and more application code is distributed via WASM to the web, how does the user agent continue to mediate the user's interest in terms of protecting privacy, security, etc.. Are the existing capability APIs and their permissions the right design approach?
* Is the web's potential growth limited when "view source" and copy-and-paste code is no longer possible (because WASM isn't really high-level enough to make sense of without source-maps or documentation).
* Is there specific guideance on what low-level APIs would make sense in this context? Currently the design-principles doc suggests text on porting ["high-level" native APIs](https://w3ctag.github.io/design-principles/#wrapper-apis) to the web, but does not cover the reverse of the spectrum.

**Comment by dbaron** [comment]
discussed a bit in Breakout B today (will try to remember to link minutes later)

**Comment by hober** [comment]
The minutes @dbaron mentioned above: https://github.com/w3ctag/meetings/blob/gh-pages/2020/telcons/05-04-minutes.md#high-level-or-low-level-apis---hober-alice-dbaron-atanassov

**Comment by LeaVerou** [comment]
I'm working on a PR for this. The minutes have a lot of good points that could seed this section, but end with:

> Alice: I'll take point on this, but would be helpful if folks can comment on the issue with concrete examples of APIs that are good and bad on this axis.

If anyone has any good concrete examples, that would be very useful!

**Comment by torgo** [comment]
Should *Don't design APIs only for framework authors* be part of this guidance?

This was brought up in our discussion of web neural network api. See minutes of breakout C for week of Feb 22.

Feedback from the requestor seemed to indicate that the API was designed for use by Frameworks rather than directly by web developers. This might be an anti-pattern? Do we need to be more explicit about this?

**Comment by LeaVerou** [comment]
Some discussion about this in [this week's plenary](https://github.com/w3ctag/meetings/blob/gh-pages/2021/telcons/03-29-minutes.md#high-level-vs-low-level)
