### ISSUE TITLE
add a section on CSS to the design principles document

### ISSUE THREAD

**Issue by dbaron** [w3ctag/design-principles#126]
Currently this document doesn't say anything about CSS; I think it should.

I think there are some sources of principles that we could pull from on the CSS working group's wiki, but I might try to frame some of them at a slightly higher level.

**Comment by dbaron** [comment]
I think it's likely useful to start with the following:
* What should be in a CSS property versus in the DOM or elsewhere
* What belongs in a single CSS property versus what should be in separate properties
* When CSS properties should be inherited or not
* How to name CSS properties and values (i.e., generally properties are nouns and values are adjectives)
* What should be resolved at the computed value stage versus the resolved value stage

**Comment by dbaron** [comment]
cc @fantasai @tabatkins since they might be interested

**Comment by fantasai** [comment]
Some links that might be useful here:
https://wiki.csswg.org/ideas/principles
http://fantasai.inkedblade.net/weblog/2019/designing-css/

**Comment by fantasai** [comment]
@dbaron Were you planning on incorporating anything from https://github.com/w3ctag/design-principles/issues/126#issuecomment-610117172 or did you find everything there to be ignorable?

**Comment by fantasai** [comment]
Also, I'm not sure why the TAG pinged me and Tab, but didn't ask the rest of the CSSWG. Do you all have something against contacting working groups, primary spec editors aside, for advice?

**Comment by dbaron** [comment]
> Were you planning on incorporating anything from #126 (comment) or did you find everything there to be ignorable?

I didn't see it; I missed the notification, and at that point the discussion was happening in the PR rather than this issue.

**Comment by LeaVerou** [comment]
It seems to me that there should be a separate CSS design principles document, authored by the entire CSS WG, and each of these should involve the relevant WG(s). HTML has (had?) [a separate design principles document](https://www.w3.org/TR/html-design-principles/), it's not all lumped together with CSS and JS.

**Comment by dbaron** [comment]
I'd note that the HTML Design Principles document is unmaintained, and we're currently [in the process](https://github.com/w3ctag/design-principles/projects/1) of merging it into this document.

I think there are advantages of a single design-principles document, such as:
* people trying to add a *capability* to the web don't necessarily know whether that capability belongs in HTML, CSS, or Javascript, or divided between them; we should expose people who are thinking about doing that to the relevant principles across all of them, and to principles that guide them towards the right place (e.g., #169).
* the TAG's design principles document being mostly about Javascript sends the message that the Web is mostly about Javascript, which I don't think is the message I want to send.

**Comment by LeaVerou** [comment]
> people trying to add a capability to the web don't necessarily know whether that capability belongs in HTML, CSS, or Javascript, or divided between them; we should expose people who are thinking about doing that to the relevant principles across all of them, and to principles that guide them towards the right place (e.g., #169).

That is indeed very useful. However, this sounds like a separate kind of document, one that should indeed be maintained in the TAG. I'm not sure that design principles of each language belong with it however. It goes against the spirit of modularization that most standardization efforts are striving towards these days, and it also means that the relevant WGs cannot contribute or participate as easily.

> the TAG's design principles document being mostly about Javascript sends the message that the Web is mostly about Javascript, which I don't think is the message I want to send.

Absolutely agreed! These design principles would also need to become a separate documet that is maintained by its own relevant WG or TF between relevant WGs. I wasn't advocating that the CSS part moves to the CSS WG and everything else stays.
