### ISSUE TITLE
Tracking, privacy, fingerprinting and user consent

### ISSUE THREAD

**Issue by torgo** [w3ctag/design-principles#13]
Straw man design principle:

Tracking of individual users on the web must always be with user consent, using established and transparent mechanisms for storage of tracking identification info with the user agent. User must always be able to determine who is tracking them using these techniques, and override them eg using private browsing modes or by flushing locally stored info. Relying on implicit tracking information (sometimes called browser fingerprinting) is not only a brittle and unreliable practice but compromises user consent and is therefore a web antipatern. Cookies, offline storage == good. Browser fingerprinting == bad.

**Comment by mnot** [comment]
FYI: http://www.w3.org/2001/tag/doc/unsanctioned-tracking/

**Comment by travisleithead** [comment]
Write a few sentances about general design based on the above linked finding.

**Comment by torgo** [comment]
Lumped in with this should be the principle of data minimization (cf my draft from ages ago here: https://www.w3.org/2001/tag/doc/APIMinimization). Not suggesting we regurgitate all of this but a principle outlining data minimization may be useful.

Alternatively we could punt on all issues related to privacy and security and refer to ta separate document for those (https://w3c.github.io/privacy-considerations/, https://www.w3.org/TR/security-privacy-questionnaire/).

**Comment by torgo** [comment]
Discussed in [11 Jan 2017 call](https://github.com/w3ctag/meetings/blob/gh-pages/2017/telcons/01-11-agenda.md). Agreed that we would explicitly not talk about security & privacy here but that we would cross-link (2nd approach outlined above). @travisleithead to implement.
