### ISSUE TITLE
Recommend that option objects are themselves optional?

### ISSUE THREAD

**Issue by jakearchibald** [w3ctag/design-principles#130]
Weirdly, I've had two separate teams ask about this today.

If an argument is a dictionary, and all members are optional, the argument itself should be optional.

```js
// This…
foo('required', {});
// …should have the same result as…
foo('required');
```

https://github.com/w3ctag/design-principles/issues/73 is kinda related.

**Comment by domenic** [comment]
This is actually enforced by Web IDL already. Trailing dictionaries are automatically optional; it's impossible to write a spec that does otherwise.

See https://heycam.github.io/webidl/#dfn-optional-argument, in particular

> If the type of an argument is a dictionary type or a union type that has a dictionary as one of its flattened member types, and that dictionary type and its ancestors have no required members, and the argument is either the final argument or is followed only by optional arguments, then the argument must be specified as optional. Such arguments are always considered to have a default value of an empty dictionary, unless otherwise specified.

**Comment by jakearchibald** [comment]
Closing since this is already enforced. Thanks @domenic!
