### ISSUE TITLE
Discourage fancy words in names

### ISSUE THREAD

**Issue by cynthia** [w3ctag/design-principles#132]
People in web standards, primarily being from a English native background have a tendency to lean towards specific, but difficult words for naming APIs. When writing a spec, this is fine - but for APIs it would be a different story.

I'm in the belief we should recommend simpler English when naming things in API space.

**Comment by marcoscaceres** [comment]
I think this is a good point, so might be good to list "good best practice" examples... like the Map and Set methods... add(), set(), has(), entries(), delete() etc. as these generally help everyone. 

I guess `querySelectorAll()` and `querySelector()` are on the opposite end. Naming things is hard.

**Comment by cynthia** [comment]
Thanks for the feedback. This was on the extreme end of this - raised while reviewing [1] getCoalescedEvents() which I personally found unapproachable. The points you mentioned should probably be added too - at the moment we only suggest what to do with "is" in naming and that seems rather narrow scoped.

[1]

**Comment by annevk** [comment]
(If a specification has a choice between a simple and a complex word I think it ought to use the simple one too, but there can be tricky tradeoffs there.)

**Comment by bkardell** [comment]
@cynthia that particular example seems unusually complex to discuss re: the particular criticisms. I'm not sure if that means it's a good example or a bad one.  For example,  one question is what is a better term here? How do you know it's better? It seems it's actually borrowing existing terms here which are used in lots of systems, so if prior art  terms and concepts already exist, I'd think that borrowing then is probably compelling as an API maker in general.. how would you balance that?

**Comment by cynthia** [comment]
@bkardell The one time I’ve seen that term used outside of that spec was in a high frequency financial analysis related textbook, I’m not sure what other uses you’ve seen but it’s not a word I’d expect the majority of the developer population to understand.

**Comment by bkardell** [comment]
@cynthia Yeah, I don't know - I've seen a lot of things use it, personally.  I'm not sure how helpful it is to discuss.  In principle I agree with the advice, and believe it is entirely plausible that is my own bias, but the spec shows that it is based on iOS's term and I've seen it in several areas - databases, filters and so on - but also non-technical things in other areas and news articles (a google search shows many uses technical and non-technical)... I guess I am just wondering if there is also advice you would give on how to judge such a thing as what constitutes a fancy word as it seems you and I would weigh the example itself differently.  If that makes sense, or is helpful in any way... Could you offer an alternative term in that case for comparison?

**Comment by dbaron** [comment]
Another point that we ran into today (which led to WICG/display-locking#127) is that we probably want to avoid using multiple very similar technical terms in developer-exposed names when sticking to just one of the terms would be enough (like both "subtree" and "descendants").
