### ISSUE TITLE
Naming things…

### ISSUE THREAD

**Issue by chaals** [w3ctag/design-principles#14]
This is of course **the** hard problem. 

A proposed rule of thumb: If you're annoyed by long names, you should probably make your name a bit longer and clearer, but if you think clear names are really important you should be trying to shorten the ones you propose.

Developers will get used to anything. But names that lead to false assumptions will result in people making a lot of costly mistakes. Names that include words that are hard to spell right (like "labeled") will be written wrongly. The people who want really short names have aliases - but really long names just discourage people from learning an actual API in the first place.

Naturally this is untestable, except when it becomes obvious what is wrong with a name. Does such advice (not necessarily this precise proposal, but something on the topic) still belong?

**Comment by domenic** [comment]
I think something along the lines of "don't take the verbose names of the past as a guide to how things should be done; we simply didn't know better" could have value.

**Comment by chaals** [comment]
The very verbose names are painful. The opaquely short ones likewise - and we run out of very short names pretty fast.

**Comment by annevk** [comment]
Do we? Fairly skeptical of that claim. Especially since most names are scoped to an object too.

**Comment by slightlyoff** [comment]
Naming is hard!

Names take meaning from signposting (the name itself), use (how people come to understand them over time), and through context (the object on the left-hand side, e.g.). Consistency can have a lot of value in helping to create a platform that users can navigate by pun and analogy. I don't think we can say more than "please consult widely on names in your APIs".

**Comment by torgo** [comment]
Agreed on Alex's wording. @travisleithead to implement.
