### ISSUE TITLE
Can we use `media` in WebNFC?

### ISSUE THREAD

**Issue by beaufortfrancois** [w3ctag/design-principles#140]
NDEF records[1] used in WebNFC begin with a type name format aka TNF. The TNF indicates the structure of the value of the type field and tells you how to interpret the type field. There are seven possible TNF values:

- 0 Empty: Empty record that has no type or payload.
- 1 Well-Known: One of several pre-defined types laid out in the NFC Forum RTD specification.
- **2 MIME media-type: An Internet media type as defined in RFC 2046.**
- 3 Absolute URI: A URI as defined in RFC 3986.
- 4 External: A user-defined value, based on rules in the NFC Forum Record Type Definition specification.
- 5 Unknown: Type is unknown. Type length must be 0.
- 6 Unchanged:  Only for middle and terminating records of chunked payloads. Type length must be 0.
- 7 Reserved: Reserved by the NFC Forum for future use.

In WebNFC, we're exposing those values as [recordType](https://w3c.github.io/web-nfc/#the-ndefrecordtype-string) and we'd like to use the word `media` for "MIME media-type".

In https://mimesniff.spec.whatwg.org/#mime-type-representation, a note says "Standards are encouraged to consistently use the term MIME type to avoid confusion with the use of media type as described in Media Queries." However, the `media` recordType would be so much better for NFC developers as it clearly identify the type of record.

> [1] an NDEF record consists of a type name format (TNF), payload type, payload identifier, and the payload. The payload is the most important part of an NDEF record; it’s the content that you’re transmitting. The TNF tells you how to interpret the payload type. The payload type is an NFC-specific type, MIME media-type, or URI that tells you how to interpret the payload. Another way to think about this is that the TNF is the metadata about the payload type, and the payload type is the metadata about the payload. The payload identifier is optional and allows multiple payloads to be associated or cross referenced. Source: https://www.oreilly.com/library/view/beginning-nfc/9781449324094/ch04.html

**Comment by beaufortfrancois** [comment]
For info, The [Media Queries specs](https://drafts.csswg.org/mediaqueries-4/#media-types) says:

> Media types have proven insufficient as a way of discriminating between devices with different styling needs ... It is expected that all of the media types will also be deprecated in time, as appropriate media features are defined which capture their important differences."

**Comment by annevk** [comment]
Why is a payload better described by a media query than a MIME type?

**Comment by beaufortfrancois** [comment]
Sorry if I wasn't clear. The "media" word would not apply to the payload, but to the "recordType" as it would refer to the MIME media type in the NDEF spec.

```js
const reader = new NDEFReader();
reader.scan();
reader.onreading = event => {
  const record = event.message.records[0];
  if (record.recordType == "media") {
    // TODO: Process record.data based on record.mediaType
  }   
}
```

**Comment by hober** [comment]
I'm happy to see that the WebNFC document has switched to adopt the web's naming convention for this field. We should update our design principles document to recommend this approach to similar cases.

**Comment by kenchris** [comment]
I guess we can close this one?

**Comment by torgo** [comment]
Closed as agreed on [call 5-10-2020](https://github.com/w3ctag/meetings/blob/gh-pages/2020/telcons/10-05-agenda.md) as we agreed to merge [this PR](https://github.com/w3ctag/design-principles/pull/217).
