### ISSUE TITLE
How do we balance concerns between interoperability and implementability?

### ISSUE THREAD

**Issue by alice** [w3ctag/design-principles#142]

**Comment by cynthia** [comment]
There is a strange variant of this, which I've seen while reviewing the [1] Shape Detection API. That API, on the same browser has different functionality depending on the underlying OS. (e.g. OCR works on Windows but not on macOS, and nothing works on Linux - or some variant of that.)

[1] https://wicg.github.io/shape-detection-api/

**Comment by hober** [comment]
@Alice to draft a PR for this, including Nigel's option -2.
