### ISSUE TITLE
Proliferation of manifests at W3C

### ISSUE THREAD

**Issue by tantek** [w3ctag/design-principles#148]
Here at #w3cTPAC 2019 I’m learning that there are quite a few different manifest file format efforts by different groups for different specifications with different but often similar use-cases. Filing this design issue per @hober’s request to track the growing number of manifest formats and approaches to hopefully collapsing and reducing them.

Here is a few I know of along with their individual TAG review issues.

  * [Web App Manifest](https://www.w3.org/TR/appmanifest/) ([W3CTAG w3ctag/design-reviews#30](https://github.com/w3ctag/design-reviews/issues/30))
  * [Payment Method Manifest](https://w3c.github.io/payment-method-manifest/) ([W3CTAG w3ctag/design-reviews#162](https://github.com/w3ctag/design-reviews/issues/162), [Payment Method w3ctag/design-reviews#27](https://github.com/w3c/payment-method-manifest/issues/27), [W3CTAG w3ctag/design-reviews#231 Payment Handler](https://github.com/w3ctag/design-reviews/issues/231))
  * [Audio Book Manifest](https://w3c.github.io/wpub/#audiobook) ([W3CTAG w3ctag/design-reviews#345](https://github.com/w3ctag/design-reviews/issues/345))
  * [Publication Manifest](https://w3c.github.io/wpub/#webidl) ([W3CTAG w3ctag/design-reviews#344](https://github.com/w3ctag/design-reviews/issues/344))

And one apparent need for a manifest: [W3CTAG w3ctag/design-reviews#218](https://github.com/w3ctag/design-reviews/issues/218). There are likely others, please add more below.

From a web author, developer, publisher perspective, it would be great if we could simplify the number of manifests, ideally one, perhaps with core properties, optional properties for specific use-cases, and a method of expanding each of those by separate working groups for maximum re-use and avoiding collisions / duplication of slightly different properties.

This issue is intended as a meta-issue just to track the growing number of manifests.

For specific proposals to provide guidelines to both spec and web authors about how to create some data and provide it in a manifest file, see: [W3CTAG w3ctag/design-reviews#95](https://github.com/w3ctag/design-principles/issues/95) (please do not mark as duplicate, I think these serve two different purposes). Thanks for your consideration!

(Originally published at: https://tantek.com/2019/261/b1/proliferation-manifests-w3c)

**Comment by torgo** [comment]
We've suggested adding a section 6.3 to the document "Manifests" with some text to the effect that specs should make use of existing manifests:

"Don't make new manifests with incompatible designs. Webapp manifest is extensible." 

Is there more we can say here?

**Comment by marcoscaceres** [comment]
We (manifest editors) screwed up in converting the spec to use WebIDL. We should caution new manifests not to use WebIDL as a data format. 

I’m hoping to convert the spec to use infra instead. The TAG should recommend extensions using infra types instead... and to discuss proposed extensions with WebApps WG! Don’t add random things. Only use WebIDL for APIs, not JSON things.

**Comment by domenic** [comment]
> "Don't make new manifests with incompatible designs. Webapp manifest is extensible."

I think this kind of blanket advice is a bit tricky. Webapp manifest has a specific design which is not suitable for all cases. See for example https://github.com/WICG/origin-policy/blob/master/policy-format.md#appendix-relation-to-web-app-manifest

**Comment by torgo** [comment]
We discussed in call March-30 and agreed to link this and #95 and work towards adding some text into the document itself which provides guidance to spec authors, including the info from this issue.

**Comment by torgo** [comment]
We agreed that the addition of PR #189 allows us to close this.

**Comment by kewisch** [comment]
As discussed with @tantek, I wanted to note there are also WebExtensions that have a [manifest.json](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json) at their root. At current this is merely a de-facto standard as it is implemented in multiple browsers. Note I am not asking for this issue to be reopened, this is just to say there continue to be more manifests related to browsers and the web possibly worth tracking.
