### ISSUE TITLE
expand on consistency of naming

### ISSUE THREAD

**Issue by dbaron** [w3ctag/design-principles#149]
We have a [section on naming](https://w3ctag.github.io/design-principles/#naming-is-hard) but reading the opening comment of w3ctag/design-reviews#341 it seems like we could expand on the principles around naming consistency a little bit.  In particular, names within a set of names (e.g., the values of an attribute/property/feature/etc.) should be:

* consistent in terms of parts of speech (noun, verb, adjective, etc.)
* consistent in negation (e.g., either all of the names in a set should describe what is allowed or they should all describe what is denied)
* (probably some more things here)

**Comment by alice** [comment]
Speculatively assigned @cynthia as this harmonises with thoughts on clear language.

**Comment by hober** [comment]
See also w3ctag/design-reviews#429

**Comment by alice** [comment]
and https://github.com/w3ctag/design-principles/issues/136

**Comment by alice** [comment]
and https://github.com/w3ctag/design-principles/issues/132

**Comment by alice** [comment]
and https://github.com/w3ctag/design-principles/issues/108

**Comment by alice** [comment]
PR: https://github.com/w3ctag/design-principles/pull/163/files
