### ISSUE TITLE
Casing rules on the platform

### ISSUE THREAD

**Issue by domenic** [w3ctag/design-principles#15]
Via @travisleithead 

Off the top of my head

- camelCase method names
- Uppercase class names
- lowercaselongconcatenated event names
- lowercaselongconcatenated or sometimes snake-case enum names (more recently snake-case... kind of inconsistent)

What else?

**Comment by marcoscaceres** [comment]
In web manifest we use underscore names for JSON members... It upsets my jscs linter tho, but oh well. Wish we would have camelCased.

**Comment by annevk** [comment]
lowercaselongconcatenated (HTML) attribute and element names. Yet camelCase property names.

**Comment by twirl** [comment]
Currently abbreviations are not written in camel case, they are capitalized as a whole (DOMElement, XMLDocument, innerHTML, etc) with minor exceptions (XMLHttpRequest). Though I don't like this rule, it's worth mentioning.
