### ISSUE TITLE
Needs an Introduction

### ISSUE THREAD

**Issue by hober** [w3ctag/design-principles#153]
The design principles document has a one-sentence abstract and no introduction. As we talked about in breakout B of 2020-02-03, we should probably add the following:

* An introduction, establishing what this document is, why we've written it, what readers can get out of it, how to read it, etc.
* Meta principles guiding the rest of the document
    * "harm reduction" was an example that came up during the call
    * [The Rule of Least Power](https://www.w3.org/2001/tag/doc/leastPower.html)
* General Web API design principles that don't have a more appropriate home elsewhere in the document or in the Ethical Web Principles, e.g. #146, #142.
    * for instance, this could be a place for the old HTML Design Principles to live. w3ctag/design-reviews#426

**Comment by hober** [comment]
Note that PR #155 adds a new section which could contain both meta principles guiding the rest of the document as well as general Web API design principles that don't have a more appropriate home elsewhere in the document.

**Comment by torgo** [comment]
Took an action today to write an intro paragraph.

**Comment by hober** [comment]
Retitled to reflect our conversation on the call today that all we need to do for now is to write an introduction.

**Comment by torgo** [comment]
This issue has been obsoleted by #191.
