### ISSUE TITLE
"Cheat sheet" for reference during design reviews?

### ISSUE THREAD

**Issue by alice** [w3ctag/design-principles#154]
We don't read our own design principles regularly, but we could probably use a refresher when we're doing reviews. Could we have a digest version to keep handy, alongside the full document?

**Comment by torgo** [comment]
@alice to start on something.

**Comment by hober** [comment]
Note that the [Security & Privacy Questionnaire](https://w3ctag.github.io/security-questionnaire/) has something like a cheat sheet: a [Markdown copy of its questions](https://github.com/w3ctag/security-questionnaire/blob/master/questionnaire.markdown) that gets [mechanically extracted](https://github.com/w3ctag/security-questionnaire/blob/master/generate-markdown.py) from the spec so it doesn't go stale.

**Comment by hober** [comment]
Assigned to myself to try adapting the security questionnaire script for this.

**Comment by atanassov** [comment]
@plinss and I looked at this during today's breakout session. We updated the links above so the right files are now linked. 
The main question we have at this point is - how is the cheat sheet supposed to differ from the TOC in the main doc? If it does then we should use a class=summary to tag specific sections. If it doesn't then there's little value in creating the cheat sheet.

**Comment by plinss** [comment]
@hober @cynthia and I reviewed this in today's VF2F and agreed to close in favor of just using the TOC
