### ISSUE TITLE
Review different cross-domain import mechanisms and their security models

### ISSUE THREAD

**Issue by tantek** [w3ctag/design-principles#157]
During #TC39 73 I’ve learned about ES Modules Attributes being proposed to address security concerns when importing JSON modules: [ES Module Attributes](https://github.com/littledan/proposal-module-attributes/). Filing this design issue for the TAG to more broadly consider various web-based cross-domain import mechanisms like [HTML Modules (334)](https://github.com/w3ctag/design-reviews/issues/334), [CSS Modules (405)](https://github.com/w3ctag/design-reviews/issues/405), and ES Modules. Specifically I request the TAG analyze and provide clarity on the exact security model or models and hopefully some degree of consistency and explicit architectural design across these mechanisms.

See the following related issues and efforts:

  * [webcomponents: HTML, CSS, and JSON modules shouldn't solely rely on MIME type to change parsing behavior #839](https://github.com/w3c/webcomponents/issues/839)
  * [Dynamic Import Host Adjustment presentation Dec 2019](https://docs.google.com/presentation/d/e/2PACX-1vQHJ-7kiplN7pzQD-GXv9icz-ySJnoMVVfGbI74oDKaeSAMdgZ3aySOR-80JGMt4Lb5oCgJ-e-BeEet/pub?start=false&amp;loop=false) ([Explainer](https://github.com/tc39/dynamic-import-host-adjustment))

From a web author, developer, publisher perspective, a more consistent and understandable security model across these would help with easier understanding and better chance of conveying author intent. Thanks for your consideration!

(Originally published at: https://tantek.com/2019/339/b1/cross-domain-import-mechanisms-security)

**Comment by hober** [comment]
Transferring. I'll take the action to write a PR for this.

**Comment by dbaron** [comment]
Here are [the minutes I mentioned from Breakout B on Monday](https://github.com/w3ctag/meetings/blob/gh-pages/2020/telcons/02-24-minutes.md#review-different-cross-domain-import-mechanisms-and-their-security-models).

**Comment by hober** [comment]
I think we should wait for the [ES Module Attributes and JSON modules](https://github.com/tc39/proposal-module-attributes) proposal to advance to Stage 3. At that point, we should do a design review of it, and evaluate if we need to add a principle here.

**Comment by hober** [comment]
I wrote:

> I think we should wait for the [ES Module Attributes and JSON modules](https://github.com/tc39/proposal-module-attributes) proposal to advance to Stage 3.

It's Stage 3 now.

> At that point, we should do a design review of it,

Done: w3ctag/design-reviews#535

> and evaluate if we need to add a principle here.

Personally, I think this issue is well in hand and we don't need to add a principle here.

**Comment by cynthia** [comment]
@hober and I discussed this during the "Cork" "F2F.

Looking at the issue at hand, while this is indeed a pretty high-impact problem generally the principles is based on specific antipatterns we have seen in API designs. For this we only have one case, so it feels like this should be treated as a design review problem and see if there are any best practices to extract from the outcome of it, which could potentially be a future principle. But for the time being, it feels a bit preemptive to write a separate section at this point.

**Comment by hober** [comment]
Resolved to close this in the breakout 11/12 summary session today.
