### ISSUE TITLE
pull things that aren't JavaScript specific into a separate section

### ISSUE THREAD

**Issue by dbaron** [w3ctag/design-principles#158]
Before I work on #126, I'd like to do a little bit of restructuring to separate parts of the design-principles document that are specific to JavaScript from parts that are cross-language.

In particular, we currently have the following two toplevel sections:

* JavaScript Language
* API Surface Concerns

What I'd like to do is rename the latter "**API Surface Concerns**" to "**Javascript API Surface Concerns**", and at the same time pull 4 of its subsections:

* Naming things
* New features should be detectable
* Use casing rules consistent with existing APIs
* Consider limiting new features to secure contexts

into a new toplevel section, perhaps called "API Design Across Languages", and put this *before* the "JavaScript Language" section.  When doing this I'd also swap the order of the middle two so that the two naming-related subsections "Naming things" and "Use casing rules consistent with existing APIs" would be next to each other.

Does this seem reasonable?

**Comment by hober** [comment]
Sounds good to me!
