### ISSUE TITLE
Warning on high precision and timing attacks

### ISSUE THREAD

**Issue by marcoscaceres** [w3ctag/design-principles#17]
This serves as a good lesson (privacy timing attack on battery API on Linux because it was reporting unnecessarily high-precision values): 
http://eprint.iacr.org/2015/616.pdf

I guess good guidance/principle would be always ask what precision is needed and how these values change over time (for one user VS for all users).

**Comment by marcoscaceres** [comment]
Spoke to one of the authors of the paper (Lukasz Olejnik), who also suggested: 

> Perhaps just expose "very low", "low", "medium", "high" and "full"?

Where appropriate, of course.

**Comment by travisleithead** [comment]
I think this may also be well-covered by the finding. See Issue 13
