### ISSUE TITLE
generic advice about preferring booleans, and maybe advice on boolean versus string versus enum

### ISSUE THREAD

**Issue by dbaron** [w3ctag/design-principles#170]
As part of review of my addition of CSS principles, @plinss [wrote](https://github.com/w3ctag/design-principles/pull/166#discussion_r404232805):

> Wondering if this should be expanded to generic advice of avoiding booleans in other apis, or possibly advice as to when to use a boolean vs a string or enum.

We also already have a section that [says to avoid boolean parameters](https://w3ctag.github.io/design-principles/#prefer-dict-to-bool) in Javascript.

So given that we've written similar advice for JavaScript and CSS, perhaps it belongs in the generic naming advice?  (And maybe we should say something about string versus enum too.)

**Comment by dbaron** [comment]
(I don't want to touch this until after both #163 and #166 land, though.)

**Comment by domenic** [comment]
There's a difference between avoiding booleans, and avoiding boolean parameters. Booleans are fine, it's just that they should be part of an options object.

**Comment by dbaron** [comment]
Yeah, maybe the advice is sufficiently different that there's not a generic version.

**Comment by dbaron** [comment]
@atanassov and I discussed this in a breakout at the TAG's virtual face-to-face and agreed to close this issue.  I don't think there's a sufficiently generic version of this advice; I think we're better off with the two current pieces of advice in https://w3ctag.github.io/design-principles/#prefer-dict-to-bool and the boolean bit of https://w3ctag.github.io/design-principles/#css-naming .
