### ISSUE TITLE
add principle on media independence (HTML Design Principle 5.1)

### ISSUE THREAD

**Issue by dbaron** [w3ctag/design-principles#173]
The HTML design principles has a section [5.1. Media Independence](https://www.w3.org/TR/html-design-principles/#media-independence).  @fantasai's [blog post](http://fantasai.inkedblade.net/weblog/2019/designing-css/#xp) also has some material that could be incorporated here (following up from https://github.com/w3ctag/design-principles/issues/126#issuecomment-610117172).

**Comment by hober** [comment]
Part of #160.
