### ISSUE TITLE
Don't call out synchronously to author code if possible

### ISSUE THREAD

**Issue by domenic** [w3ctag/design-principles#18]
It allows observability of steps that otherwise could be optimized, cached, etc.

**Comment by travisleithead** [comment]
While the UA is processing steps, synchronous callouts to author code have other potential bad side-effects. Consider:
* focus() and onfocus event handlers (run as part of the focus steps). These are synchronous callouts to author code that can lead to re-entrant behavior if the author code calls focus() on something else. (This is solved by using a "focus lock" applied to an element that provides an exit condition for the focusing algorithm when re-entered synchronously on the stack.) If not for this condition, then there is a potential stack-overflow.

Ideally, if needed, the call-out should be moved to a "safer" location, such as a Nano-task or micro-task checkpoint, or queued into a task queue for a subsequent turn of the event loop.

**Comment by torgo** [comment]
@travisleithead to integrate this text into doc.

**Comment by dbaron** [comment]
We already have https://w3ctag.github.io/design-principles/#favor-asynchronous-events -- though maybe we should add some things to it.
