### ISSUE TITLE
Remove our custom DOMHighResTimeStamp anchor

### ISSUE THREAD

**Issue by hober** [w3ctag/design-principles#181]
Now that the term is exported: w3c/hr-time#90

**Comment by marcoscaceres** [comment]
Just to confirm, the term is exported and in Shepherd: 
https://respec.org/xref/?term=DOMHighResTimeStamp

**Comment by hober** [comment]
> Just to confirm, the term is exported and in Shepherd:
> https://respec.org/xref/?term=DOMHighResTimeStamp

Thanks @marcoscaceres!
