### ISSUE TITLE
incorporate some of CSS2's design principles

### ISSUE THREAD

**Issue by dbaron** [w3ctag/design-principles#188]
[Håkon Wium Lie](https://wiumlie.no/) wrote [pointing out](https://lists.w3.org/Archives/Public/www-style/2020May/0010.html) that CSS2 has [a set of design principles](https://www.w3.org/TR/CSS2/intro.html#design-principles) some of which may be worth incorporating into this document.  (I think some are already present, and some already have issues on file to add them.)

**Comment by torgo** [comment]
@dbaron we're just taking a look at this. From your PoV has this been accomplished? Can we close this issue?

**Comment by LeaVerou** [comment]
Hi @dbaron, we reviewed this section today, and out of these principles, we couldn't find something we felt would enrich the Design Principles document. They are either already covered, too vague, or obvious at this point. Therefore, we are going to go ahead and close this, but feel free to reopen if there are specific CSS 2 principles you feel we should add.
