### ISSUE TITLE
New Title & Abstract

### ISSUE THREAD

**Issue by torgo** [w3ctag/design-principles#191]

**Comment by torgo** [comment]
Out put of breakout discussion with @Alice and myself:

Suggested new title: “Web API Design Principles”

Remove: "collection of ideas" status and move this to become a Note (as per discussion with AB).

Suggested new subtitle: “This document contains a set of design principles collected by the W3C TAG while reviewing specifications. The TAG encourages any developers of new web specifications to read this document and/or use it as a reference.”

**Comment by annevk** [comment]
I wonder if "Web Platform" might better reflect the inclusion of CSS and manifests and other technologies that might not immediately jump to mind when you see the word API.

I would favor a somewhat bolder Abstract, e.g., "This document contains a set of design principles to be used when designing Web Platform technology."

**Comment by hober** [comment]
> Remove: "collection of ideas" status and move this to become a Note (as per discussion with AB).

Fixed in https://github.com/w3ctag/design-principles/pull/183.
