### ISSUE TITLE
We need an acknowledgment section

### ISSUE THREAD

**Issue by torgo** [w3ctag/design-principles#192]
As discussed in one of our f2f Breakouts between Ken & myself, we need an acknowledgment section to acknowledgment all the input from various people who have contributed to this doc.

**Comment by kenchris** [comment]
We should make make the TAG the editor for the "spec" and all all of us (former and current members who contributed) in the ack section, plus everyone else who contributed in one way or the other. It probably requires a bit of digging to find out who contributed

**Comment by hober** [comment]
I started working on this today.
