### ISSUE TITLE
Can we change the title to say "web API"?

### ISSUE THREAD

**Issue by hadleybeeman** [w3ctag/design-principles#20]
So much of our community also works with data APIs (even related to web stuff — see the Data on the Web Best Practices Working Group), and implying this covers all APIs may cause some confusion.

**Comment by mnot** [comment]
"browser API"?

**Comment by hadleybeeman** [comment]
That should clear up the confusion. Let's go with that.

**Comment by torgo** [comment]
We agreed "client side APIs" - @travisleithead to make the change
