### ISSUE TITLE
Consider pulling feedback from CSSWG into this doc regarding shipping experimental features

### ISSUE THREAD

**Issue by travisleithead** [w3ctag/design-principles#21]
See: https://drafts.csswg.org/css-2015/#experimental

**Comment by domenic** [comment]
Hmm, that's a tough one. It's not really about API design, but more about browser-shipping-policy design. I.e., it's not like anyone actually specifies an API whose name starts with "webkit".

**Comment by travisleithead** [comment]
Indeed. I'm not wedded to the idea either--however, it was suggested that this be something that the TAG consider, rather than something local to the CSSWG. Now we at least have a talking point :)

**Comment by domenic** [comment]
Yeah that definitely makes sense. Still not sure the W3C's word would actually make a difference here, but yeah it's definitely wider than just CSS.

**Comment by slightlyoff** [comment]
We're going to discuss this at this week's face-to-face in Melbourne

**Comment by travisleithead** [comment]
We're still not sure if this advice for implementers belongs in this document, but we're going to stick it in there for now, and then we'll at least have some text to move somewhere else later (if we want).

**Comment by travisleithead** [comment]
Perhaps we should just let this go instead...

**Comment by slightlyoff** [comment]
Discussed at today's F2F. It's hard to make broad guidance here. Engine vendors are already moving things towards systems like [Origin Trials](https://www.chromium.org/blink/origin-trials), and I think we'd encourage that...which largely sidesteps the question.

Closing this. If folks feel guidance here is both something that would be warranted and effective, happy to revisit, but it seems outside our scope at the moment.
