### ISSUE TITLE
Extend Other API Considerations section to include expanded impacts

### ISSUE THREAD

**Issue by brodrigu** [w3ctag/design-principles#212]
The Web Platform Design Principles document includes a number of items under section 9. Other API Design Considerations including the work of the team in drafting the [Security Questionnaire](https://github.com/w3ctag/security-questionnaire/) to help authors identify the impacts of their proposal on user security provides a valuable resource.

However, new features and specifications can have far reaching impacts on users beyond the important considerations of privacy and security. These could include positive and negative impacts to freedom, competition, and innovation.

Expanding section 9 to help authors identify these issues in their proposals as well as providing a framework for comparing these considerations against those of privacy and security would facilitate more inclusive and rigorous proposals and a stronger web.

**Comment by jwrosewell** [comment]
Agree. There are a broader set of concerns including harms associated with discrimination, freedom of expression and democracy that should be considered. There is an [issue associated with the Security Questionnaire](https://github.com/w3ctag/security-questionnaire/issues/85) of relevance.

**Comment by torgo** [comment]
We discussed in TAG breakout today and came to the consensus that the social considerations belong in the [ethical principles](https://www.w3.org/2001/tag/doc/ethical-web-principles/) doc and should be called out from the design principles more explicitly (and clarifies the relationship between the 2 docs)?  We're going to work on a PR that does that. Hence I'm going to close this issue.   And we're going to continue working on the ethical principles doc as well.
