### ISSUE TITLE
JavaScript is growing multiple numeric types

### ISSUE THREAD

**Issue by bzbarsky** [w3ctag/design-principles#23]
Section 2.1 talks about JavaScript having only one numeric type, but that's going to change (e.g. real 64-bit integers will get added).  This section should probably take that into account.

**Comment by domenic** [comment]
There isn't any proposal accepted, even at the strawman stage, for such a thing...

**Comment by bzbarsky** [comment]
I was under the distinct impression that there were explicit plans for such.  Maybe I was misinformed, of course....

**Comment by travisleithead** [comment]
@domenic any progress on other numeric types being defined? I.e., do we need to update the guidance here in the short term?

**Comment by torgo** [comment]
On hold for now.

**Comment by travisleithead** [comment]
(Big number support is expected in ECMAScript soon--may want to come back to this after that is done.)
