### ISSUE TITLE
Casing rules should probably call out HTML IDL vs content attributes

### ISSUE THREAD

**Issue by annevk** [w3ctag/design-principles#24]
E.g., `referrerpolicy` is good for a content attribute, but its corresponding IDL attribute has to be `referrerPolicy`. This follows from the table, but is probably good to call out explicitly.

**Comment by domenic** [comment]
Is the explicit distinction between property/method and HTML attribute not enough?

**Comment by domenic** [comment]
Oh, you are talking about when there is an attribute with a corresponding property (IDL "attribute"). Yeah a note on that case makes sense. Thanks.
