### ISSUE TITLE
New principle: all new headers shall be structured headers

### ISSUE THREAD

**Issue by annevk** [w3ctag/design-principles#252]
To not expand on the number of custom header parsers in HTTP libraries, all new headers must follow https://tools.ietf.org/html/draft-ietf-httpbis-header-structure. This is already de facto enforced, but it would be good to have it documented.

cc @mnot (feel free to unsubscribe, but I thought you might want to know)

**Comment by LeaVerou** [comment]
If we resolve to work on this, I wonder if this means we should add a new section for HTTP-related principles?

**Comment by cynthia** [comment]
https://w3ctag.github.io/design-principles/#new-http-header-syntax

**Comment by torgo** [comment]
Discussing today and we think we can close this.
