### ISSUE TITLE
New principle: Inclusive Naming Choices

### ISSUE THREAD

**Issue by torgo** [w3ctag/design-principles#253]
This was brought up in our discussion of the chairs meeting at this year's TPAC. @jeffjaffe suggested we could recommend that people should avoid names that do not promote inclusivity. One example I can think of is "black lists" vs. "block lists".

**Comment by jeffjaffe** [comment]
... or any terminology with a master/slave component...

**Comment by LeaVerou** [comment]
Since there's a merged PR, we're closing this!
