### ISSUE TITLE
Clarity in the "user"

### ISSUE THREAD

**Issue by neilmcn** [w3ctag/design-principles#259]
In the Design Principles Note(1) ([https://www.w3.org/TR/2020/NOTE-design-principles-20201110/]) it says "If a trade-off needs to be made, always put user needs above all." It might be good to clarify who is the user of "design principles". It might be a good idea to think of the developer or the development team in this context, and to make a distinction between the developer as user and the browing end user of the GUI.
This is not exactly a trivial issue. Lok at the source code of just about any web page - reams and reams of hard to maintain idiosycracies.
Compare this with our own site (2) (https://www.oilit.com) which offers rich functionality with a few lines of code. Yes it uses the deprecated and marked-for-removal frameset. 
Makes you think....
1) https://www.w3.org/TR/2020/NOTE-design-principles-20201110/
2) https://www.oilit.com

**Comment by cynthia** [comment]
I believe we differentiate terminology here - developers are specifically denoted as "developer". User in this context is "anyone who uses the web". (Users would obviously also include developers, spec authors, etc.)

**Comment by cynthia** [comment]
Closed based on plenary discussion during F2F today.
