### ISSUE TITLE
Triage issues that should block a first publication

### ISSUE THREAD

**Issue by travisleithead** [w3ctag/design-principles#26]
At Melbourne TAG f2f, we talked about progressing this document to an eventual first publication, with the expectation that there would be follow-up publications as we address additional issues.

**Comment by domenic** [comment]
My understanding was that this would not be a snapshotted document that goes through the process. In that case "publication" just means giving it a w3.org proxy URL. That is the same procedure as the promises guide.

**Comment by torgo** [comment]
Agreed to close in [Feb 2017 f2f](https://github.com/w3ctag/meetings/tree/gh-pages/2017/02-boston).
