### ISSUE TITLE
Feedback on "11.1. Use common words"

### ISSUE THREAD

**Issue by riannella** [w3ctag/design-principles#261]
In the "11.1. Use common words" section:

1 - It would be difficult to mandate the use of "US English". This should be reworked to indicate the human language used should address the target community.

2 - The example "setSize is a more English-readable name than cardinality" - these two concepts are completely different, so not really a "readability" issue.

**Comment by cynthia** [comment]
> It would be difficult to mandate the use of "US English". This should be reworked to indicate the human language used should address the target community.

This is based on de-facto what we have in all the specs. Currently, the lingua franca of the community (while not ideal, we don't have anything better) is English - and I don't think broadening the wording here

> these two concepts are completely different

How so? https://en.wikipedia.org/wiki/Cardinality

**Comment by cynthia** [comment]
Closed based on plenary discussion during F2F today.

**Comment by csarven** [comment]
@cynthia If the discussion was minuted, can you please link to it? Alternatively, and I understand that this was a while back, but could you share a summary here?

Related: https://github.com/w3ctag/design-principles/issues/499

**Comment by cynthia** [comment]
Skimming https://github.com/w3ctag/meetings/tree/gh-pages/2024/01-london I don't think this was minuted. As editor my memory of the discussion was "current API naming is US English spelling, for consistency we shouldn't change the guidance" and "I don't understand how set size is different from cardinality - Wikipedia literally calls it out". Hope this helps.
