### ISSUE TITLE
New principle: Discourage language sniffing for language-specific features

### ISSUE THREAD

**Issue by cynthia** [w3ctag/design-principles#266]
This was brought up in our discussion of auto-hyphens in https://github.com/w3ctag/design-reviews/issues/581.

In essence, auto-hyphens are language-specific, and in this particular case the spec opted for this feature to only work when the language was explicitly specified. Since we are proposing a similar direction of discouraging sniffing/heuristics for mime types, we believe that we should also discourage new features from sniffing for the target language.

**Comment by timbl** [comment]
If the user has logged in with Solid then the App then the app should have  access to their language preferences.

**Comment by cynthia** [comment]
Discussed in the plenary today, and we don't think there are enough common patterns here (especially, bad practices) that would warrant us writing this as a principle. We will revisit when there are more cases.
