### ISSUE TITLE
[Meta] HTML Design Principles section

### ISSUE THREAD

**Issue by LeaVerou** [w3ctag/design-principles#269]
Currently the Design Principles document has separate sections for CSS-specific and JS-specific principles, but not for HTML. 

We should have a section for HTML, potentially including things like:
- Some of [these guidelines](https://w3ctag.github.io/webcomponents-design-guidelines/#native-html-elements) could be folded in 
- As we progress on #160 we may find that some of the old HTML Design principles are indeed HTML design principles and not more broadly web platform design principles, so a section on HTML could include them.
- Other things such as when to use an attribute vs a child element or how to represent certain kinds of data via attributes could go there too.

**Comment by LeaVerou** [comment]
Broad consensus in breakout A & B that we should do that.

**Comment by LeaVerou** [comment]
Since we now [have an HTML section](https://w3ctag.github.io/design-principles/#html) and all the individual principles discussed have their own issues, we are going to go ahead and close this.

**Comment by torgo** [comment]
Closed with #326
