### ISSUE TITLE
HTML: Guidance about URL-containing attributes

### ISSUE THREAD

**Issue by LeaVerou** [w3ctag/design-principles#278]
This relates to #269.

Naming:

If the URL is central to the element's purpose, then it should be named `href` or `src`, for consistency:
- `src` for embedded content (e.g. `<audio>`, `<embed>`, `<iframe>`, `<img>`, `<input>`, `<script>`, `<source>`, `<track>`, `<video>`)
- `href` for linked content (e.g. `<a>`, `<area>`, `<base>`, `<link>`)
- The difference can be murky...

Antipatterns in existing HTML:
- `<object data>`
- `<applet code>`

These are not antipatterns, because the URL is not central to the element's purpose:
- `<video poster>`
- `cite` attribute in `<blockquote>`, `<del>`, `<ins>`, `<q>`
- `<a ping>`

What about `<form action>` (and the `formaction` attribute)? Should it have been `<form href>` or is there another rule at play?

Additional notes:

- Relative URLs should be relative to the current document
- Should the IDL attributes reflecting these return a `URL` object? Currently, for most of these elements, the IDL attribute returns the serialized absolute URL. Some include additional attributes that effectively mirror `URL` object properties (e.g. `pathname`, `host` etc). I seem to recall there was a WHATWG guideline

**Comment by cynthia** [comment]
This should be tied with a principle for any APIs (or CSS properties) that accept URLs as well.

**Comment by LeaVerou** [comment]
We discussed this in a breakout today. We agreed there should be a principle recommending `src` for embedded content (loading semantics) and `href` for linked content.
We are not sure about `<form action>`.
We briefly discussed if there should be any additional naming guidance for the secondary URL attributes in the 3rd list.
We will discuss the last two issues in the plenary.

**Comment by hober** [comment]
On the call today @ylafon and I made the argument that `<form action>` shouldn't have been `href` because `<form>` is capable of invoking unsafe HTTP verbs. If `<form>` had been limited to just `GET`, maybe it would have made sense for it to be named `<form href>`, since in that world it's just a fancy form of navigation, but that's not the world we find ourselves in.

**Comment by cynthia** [comment]
Quick notes from F2F discussion:

- `href` implies ability to navigate to
- `src` implies (implicit) fetching
- `poster` and `cite` serve auxiliary purposes
- Overloading is bad: <link> we might want to consider an antipattern
- We should update the Web Components guidelines for this - link back?

@hober to write.

**Comment by LeaVerou** [comment]
Should `<use href>` have been `<use src>`? That's what our current guidance seems to imply.
