### ISSUE TITLE
Prefer dictionary over a boolean parameter

### ISSUE THREAD

**Issue by annevk** [w3ctag/design-principles#28]
We should have this as advice. And we should note that boolean dictionary members need to default to false, although this would be redundant with IDL.

This ensures the API is:
- More easily extensible
- Less ambiguous when used (what is true?)

**Comment by domenic** [comment]
Probably reference http://ariya.ofilabs.com/2011/08/hall-of-api-shame-boolean-trap.html

**Comment by annevk** [comment]
https://github.com/WICG/EventListenerOptions/issues/33 has some further thoughts on booleans.
