### ISSUE TITLE
HTML: Re-use existing attribute names for similar concepts

### ISSUE THREAD

**Issue by LeaVerou** [w3ctag/design-principles#281]
New elements should try to re-use existing attribute names for similar concepts.

Examples:
- The `multiple` attribute is used in both `<select>` and `<input type=file>`
- The `open` attribute was introduced in `<details>` and re-used for `<dialog>`
- The `for` attribute is used in both `<label>` and `<output>`

(I did not include the numerous cases of the same attribute being used across multiple elements for the same thing, e.g. `src` or `type`)

**Comment by annevk** [comment]
(`type` might be a case where it has been reused too much as its value space is not consistent across elements.)

**Comment by LeaVerou** [comment]
> (`type` might be a case where it has been reused too much as its value space is not consistent across elements.)

Ooooh good point. This should be mentioned as an antipattern.

**Comment by LeaVerou** [comment]
This came up in https://github.com/w3ctag/design-reviews/issues/599

Context: The proposal introduced an `anchor` attribute (`<popup anchor="someId">`), I recommended they use `for` as this is very similar usage to `<label for>` and `<output for>`.

**Comment by torgo** [comment]
@LeaVerou will make a go of writing a PR for this.

**Comment by LeaVerou** [comment]
> @LeaVerou will make a go of writing a PR for this.

Done: https://github.com/w3ctag/design-principles/pull/326
