### ISSUE TITLE
Link with Ethical Web Principles

### ISSUE THREAD

**Issue by rhiaro** [w3ctag/design-principles#282]
* Make clear the relationship between the Design Principles and the [Ethical Web Principles](https://www.w3.org/2001/tag/doc/ethical-web-principles/) with some introductory text in section 1
* Check through the Design Principles for places to cross link to specific relevant subsections the Ethical Web Principles

**Comment by torgo** [comment]
1.2 should reference https://www.w3.org/2001/tag/doc/ethical-web-principles/#privacy

1.3 should reference https://www.w3.org/2001/tag/doc/ethical-web-principles/#verify

1.4 should reference https://www.w3.org/2001/tag/doc/ethical-web-principles/#control and maybe privacy as well

1.5 should reference https://www.w3.org/2001/tag/doc/ethical-web-principles/#multi

**Comment by torgo** [comment]
We agreed to close based on merging https://github.com/w3ctag/design-principles/pull/327
