### ISSUE TITLE
New design principle: Consistency

### ISSUE THREAD

**Issue by LeaVerou** [w3ctag/design-principles#285]
Consistency is currently mentioned in [Naming](https://w3ctag.github.io/design-principles/#naming-consistency), but I think it's broader than naming and should really have its own section, which naming could reference.

A few thoughts:

I think we probably all agree that all else being equal, consistency with the rest of the Web Platform should be prioritized. However since typically all else are *not* equal, there are tradeoffs to be made, and we should provide guidance about how to resolve these dilemmas.

* Since the Web Platform has gradually evolved over time, there are often multiple conflicting precedents. We should provide some guidance about which precedent to choose in these cases. It seems that a reasonable guideline might be to choose based on prevalence, API ergonomics, and to prioritize newer APIs over older ones. Not sure about the relative order of these three factors.
* There is often a tension between API ergonomics and internal consistency, when precedent is very clearly of poor usability. In some cases it makes sense to break consistency to improve usability, but the improvement in usability should be very significant to justify this.
* There is often a tension between [internal and external consistency](https://www.nngroup.com/articles/consistency-and-standards/#articleBody:~:text=A%20Continuum%20of%20Consistency). That might materialize in three layers: consistency within the technology (e.g. CSS) vs consistency with the rest of the Web Platform vs consistency with the rest of the world. One example is Lab colors: It would be more consistent with CSS to use `<percentage>` for L (0%-100%), but more consistent with the color science world to use a `<number>` (0-100). There was a lot of heated debate, which [resolved](https://drafts.csswg.org/css-color-4/#specifying-lab-lch) in favor of consistency within CSS, i.e. percentages.

This is partly related to the [Pave the Cowpaths HTML Design principle](https://www.w3.org/TR/html-design-principles/#pave-the-cowpaths). Do we want to merge them?

**Comment by hadleybeeman** [comment]
Would be interesting to explore how these thought might be a counterpart to the [W3CTAG Evergreen Web finding](https://www.w3.org/2001/tag/doc/evergreen-web/).

**Comment by LeaVerou** [comment]
Another example by @plinss : It would be cool if API methods that return URLs actually returned `URL` objects, but there are so much existing API surface that returns strings, that it would be inconsistent. So it's another instance of API ergonomics (`URL` objects) vs internal consistency (strings).

**Comment by ylafon** [comment]
Note that we already have a section on units relative to consistency, see https://w3ctag.github.io/design-principles/#types-and-units that probably need expansion or link to WG-produced document about consistency.

**Comment by torgo** [comment]
Could we use wake lock as an example?

**Comment by torgo** [comment]
On further reflection and considering our work load we are going to close this for now. If we get further feedback on the doc regarding lack of examples we can re-open.
