### ISSUE TITLE
Clarify if event handler attributes need definition (and if so, under what conditions)

### ISSUE THREAD

**Issue by wolenetz** [w3ctag/design-principles#29]
For more context, see https://github.com/w3c/media-source/issues/66 for more context, especially the chain of comments up to the reply by @domenic (https://github.com/w3c/media-source/issues/66#issuecomment-215540130).

Under what conditions should event handler attributes be defined in a spec? Should they be for only "declarative" objects (like `<video>`), or for any object that inherits from EventTarget, or some other conditions?

Note that both MSE and EME specs currently operate under the assumption that event handlers only need definition for declarative objects. For example, "MediaSource.onsourceopen" is not defined, since MediaSource objects can only be created by script. Script must explicitly listen for "sourceopen" event firing on a MediaSource to handle that event.

@ddorwin, @foolip, @jdsmith3000, @paulbrucecotton for getting updates on the status of this issue.

**Comment by domenic** [comment]
It should be any object that inherits from EventTarget. There's no rationale for restricting it to any class of objects, whether that restriction is "element interfaces" or "interfaces that start with the letter Q". The benefits are the same for all interfaces.

**Comment by annevk** [comment]
Event handlers are not magical. They're just ordinary IDL attributes and therefore need to be defined.

**Comment by wolenetz** [comment]
@annevk Magic was not suspected here :).
It was more of a current vs legacy style question, since (per the original comment linked for context) there appears to not have been such clarity in the past.
