### ISSUE TITLE
Inconsistent capitalisation of "web platform"

### ISSUE THREAD

**Issue by rhiaro** [w3ctag/design-principles#294]
Sometimes it's Web Platform, sometimes Web platform, sometimes web platform.

**Comment by LeaVerou** [comment]
IMO we should go with Web Platform, as it's a proper noun.

**Comment by torgo** [comment]
Can we get 👍🏻 for all caps (Web Platform) and 👎🏻 for all lower (web platform)?

**Comment by cynthia** [comment]
We also have two instances of "Web platform".

**Comment by kenchris** [comment]
https://www.wired.com/2016/04/ap-finally-realizes-2016-will-let-us-stop-capitalizing-internet/

**Comment by annevk** [comment]
https://whatwg.org/style-guide#casing

**Comment by hober** [comment]
Expanding a bit on @annevk's comment, the [W3C Manual of Style](https://w3c.github.io/manual-of-style/#Terms) is okay with "web" or "Web" in a phrase, whereas the WHATWG Style Guide prefers "web" unless it's the first word in a sentence. Given this, we should probably match the WHATWG style.
