### ISSUE TITLE
Guidance for when to use inheritance vs composition

### ISSUE THREAD

**Issue by plinss** [w3ctag/design-principles#298]
This was brought up in our discussion of https://github.com/w3ctag/design-reviews/issues/587.

In the example spec, there's a question if the color select event should inherit from a PointerEvent, or should be a new event type that contains an optional reference to the pointer event.

This raises the general question, of when should we recommend composition vs inheritance. We should do some spelunking and look for existing patterns.

**Comment by martinthomson** [comment]
https://en.wikipedia.org/wiki/Liskov_substitution_principle is a nice starting point for this.

**Comment by LeaVerou** [comment]
I cannot find the discussion that prompted this, but generally inheritance is for "is a" relationships, while composition of the type described in the OP (a property pointing to another object) is for modeling all other types of relationships.
The Liskov substitution principle is a good test for this.
