### ISSUE TITLE
Simple things should be easy, complex things should be possible

### ISSUE THREAD

**Issue by LeaVerou** [w3ctag/design-principles#299]
From [this week's plenary](https://github.com/w3ctag/meetings/blob/gh-pages/2021/telcons/03-29-minutes.md#high-level-vs-low-level)

> Lea: I think a good API isn't one point in the continuum of low level and high level, it progressively reveals more abilities as you need them. Can start very hgih level, sensible defaults, simple things are easy, and progressively you can customise what it does for complex use cases. That is the ideal. Simple things are easy and complex things are possible.
> 
> Dan: I like that wording. Maybe we do need a simple things should be easy principle.

Also related to #117 

Actually, maybe it should be "Common things should be easy, complex things should be possible".
The common case is not necessarily simple (e.g. see Sanitizer API), but that's the one we should optimize for.

**Comment by annevk** [comment]
Bikeshed: Common things should be as straightforward as possible while not precluding complex things.

**Comment by LeaVerou** [comment]
> Bikeshed: Common things should be as straightforward as possible while not precluding complex things.

Agreed, in principle. If you had specific examples in mind while writing this, please share them, they'd be useful!

**Comment by annevk** [comment]
I guess I was mainly thinking of `fetch()` where we have made a lot of these tradeoffs. In particular designing it for low memory usage and performance, providing the full HTTP API, not compromising security, etc. I'm a bit hard-pressed to come with succinct examples though.
