### ISSUE TITLE
New principle: Patterns for URLs in APIs

### ISSUE THREAD

**Issue by cynthia** [w3ctag/design-principles#303]
This was spun out of the discussion here: https://github.com/w3ctag/design-principles/issues/278

URLs are used all over the web platform. We unfortunately don't have any guidance on it aside from the occasional one-off comment when we see an antipattern in a review.

1. Best practices for APIs which accept or emit URLs
2. Best practices for URLs as part of state
3. Guidance on what to do when one needs to implement a URL-like object (e.g. https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate)

**Comment by ylafon** [comment]
@jyasskin @matatk discussed this a bit. Trying to find examples or usage of URLs in APIs. Many are using `url`, `urls`. Some other includes URL in their name like `baseURL`, `documentURL`, etc... But it is pretty difficult to get a comprehensive list of all the API consuming URLs as they are using `USVString` (or sometimes, wrongly `DOMString` to represent URLs).

@cynthia do you have specific anti-pattern examples that could help?

**Comment by annevk** [comment]
There is guidance btw: https://url.spec.whatwg.org/#url-apis-elsewhere

**Comment by jyasskin** [comment]
Thanks @annevk. Given that, I think the action here is to add a very short section that cites the guidance in URL.
