### ISSUE TITLE
New principle: When to use client hints

### ISSUE THREAD

**Issue by torgo** [w3ctag/design-principles#307]
This was brought up in our discussion of [client hints reliability mechanism](https://github.com/w3ctag/design-reviews/issues/549) - in breakout A on [week-of April 19](https://github.com/w3ctag/meetings/blob/gh-pages/2021/telcons/04-19-agenda.md). The question was raised : should we have a design principle on when to use / not use client hints as opposed to other mechanisms?

**Comment by torgo** [comment]
Came up in discussion of https://github.com/w3ctag/design-reviews/issues/632 - maybe we should say that client hints should always be an optimisation - that you should always be able to accomplish whatever the goal is with some other means.

**Comment by yoavweiss** [comment]
> maybe we should say that client hints should always be an optimisation - that you should always be able to accomplish whatever the goal is with some other means.

Can you expand on why that would be the case? That used to be the assumption, but the Client Hints reliability mechanism is explicitly trying to solve this (by making Client Hints reliable and predictably available).

**Comment by torgo** [comment]
The perception we have is that client hints are more difficult to use for web developers because they require access to server configuration. So they're fine for "big web" but present a barrier to entry for others. Also in some cases client hints are disabled. Let's have a discussion about it by all means.

**Comment by torgo** [comment]
Some good discussion in our call today https://github.com/w3ctag/meetings/blob/gh-pages/2021/telcons/06-14-agenda.md that should enable us to write some text.

**Comment by yoavweiss** [comment]
Thanks Dan! The [Security Considerations](https://datatracker.ietf.org/doc/html/rfc8942#section-4) section of the RFC can provide a good overview of the principles we used so far.
