### ISSUE TITLE
Principle against tying APIs too closely to hardware

### ISSUE THREAD

**Issue by LeaVerou** [w3ctag/design-principles#308]
This was brought up in our breakout today while [reviewing Compute Pressure](https://github.com/w3ctag/design-reviews/issues/621)

@hober had some interesting examples from past reviews, could you share them here please?

**Comment by cynthia** [comment]
I think this is related to https://github.com/w3ctag/design-principles/issues/39 so I'll see if I can write a PR that deals with both of these issues.

**Comment by cynthia** [comment]
I think this should be covered here, let me know if you there is something that we missed.
https://w3ctag.github.io/design-principles/#usecase-oriented-apis
