### ISSUE TITLE
New principle: Guidance on User Activation

### ISSUE THREAD

**Issue by torgo** [w3ctag/design-principles#314]
This was brought up in our discussion of our special session on WebID with Sam Goto and friends: https://github.com/w3ctag/meetings/blob/gh-pages/2021/telcons/05-17-agenda.md.

Sam asked if we had specific guidance about when something should require a user gesture or user activation. As it turns out the word "activation" doesn't appear in the design principles. So should we have a principle about when user activation or a user gesture should be required? Is the concept of **user activation** defined anywhere that we can lift from? How can we relate this to the Ethical Web Principles? Should this be its own principle or something that we add to "safe to browse"?

**Comment by annevk** [comment]
FYI: https://html.spec.whatwg.org/#tracking-user-activation defines the core concept.

**Comment by torgo** [comment]
Also ref https://github.com/w3ctag/design-reviews/issues/636#issuecomment-853319479

**Comment by hober** [comment]
Closing as we [added such a principle](https://github.com/w3ctag/design-principles/pull/365) last year.
