### ISSUE TITLE
Overall readiness

### ISSUE THREAD

**Issue by svgeesus** [w3ctag/design-principles#316]
The TAG design principles look very good overall. I'm aware they are still being elaborated (but that is true of any active, maintained specification).

Is this ready to be generally promoted? For example, should new W3C Working Group charters include a sentence along the lines of

> We expect to follow the [TAG Design Principles](https://w3ctag.github.io/design-principles/)

Or would you prefer that the document is more mature?

(This [came up](https://github.com/w3c/charter-drafts/issues/303) in the context of maintaining the [W3C WG and IG charter template](https://github.com/w3c/charter-drafts))

**Comment by annevk** [comment]
I would expect that. We definitely use them in WHATWG land in that way. cc @domenic

**Comment by LeaVerou** [comment]
Hi Chris,

We just discussed this in our plenary and all of us who were present agreed that we *do* feel the document is mature enough for such wording to be included in WG charters.

Thank you for checking with us!
