### ISSUE TITLE
Avoid recommending DOMTimeStamp

### ISSUE THREAD

**Issue by yoavweiss** [w3ctag/design-principles#332]
`DOMTimeStamp` is not well-defined, and we're trying to avoid it in new APIs. See https://github.com/heycam/webidl/issues/2#issuecomment-909364883 for the full discussion.

It'd be good to change https://w3ctag.github.io/design-principles/#times-and-dates to reflect that.

**Comment by LeaVerou** [comment]
What should we recommend instead? `DOMHighResTimeStamp`? I skimmed through the linked discussion but wasn't sure.

**Comment by yoavweiss** [comment]
Yes, apologies for not making it clearer. `DOMHighResTimeStamp` should be the recommended type for any timers.
