### ISSUE TITLE
New principle: Ethical Principles

### ISSUE THREAD

**Issue by mprorock** [w3ctag/design-principles#338]
The topic of Ethical, Social, and Environmental principles as being of key importance for inclusion in specs/notes and other guidance to developers was brought up in review of the DID spec during discussion around [objections to the DID spec](https://www.w3.org/2021/09/21-did10-minutes.html).

This should likely include reference to the [Ethical Web Principles](https://www.w3.org/2001/tag/doc/ethical-web-principles/)

**Comment by OR13** [comment]
@mprorock thanks for raising this issue. 

As noted on on the other linked issue: https://github.com/w3ctag/design-principles/issues/239

These objections were note raised during the TAG review: https://github.com/w3ctag/design-reviews/issues/556#issuecomment-763900128

However, I am supportive of refining guidelines such that future work and TAG reviews can refer to guidance that has been developed through a collaborative consensus driven process.

We attempted some related language here, https://github.com/w3c/did-imp-guide/pull/27 however, much of the proposed language was rejected, and the conversation clearly demonstrated that technical experts do not agree on how ESE principles apply to abstract data models such as RDF or JSON.

Stronger requirements from the TAG could assist future working group members develop language specific and relevant to their specification.

Its important to remember, "We shape our tools, and thereafter our tools shape us"... 

The AI community has been contemplating what shape GPT-3 will create:

- https://www.wired.com/story/efforts-make-text-ai-less-racist-terrible/

Th digital identity community wondering what shape mDL will create:

- https://www.eff.org/document/2021-07-29-aclu-eff-epic-comments-re-dhss-mdl

**Comment by OR13** [comment]
At the crux of some of the toughest ethical questions is how much are "values worth"... for example, bitcoin could be the most expensive environmentally destructive decentralized database ever created, but if it prevents a journalist from being censored or an organization from being cut off from the financial world... 

- [Visa, MasterCard Move To Choke WikiLeaks](https://www.forbes.com/sites/andygreenberg/2010/12/07/visa-mastercard-move-to-choke-wikileaks/)

.. some folks might view that cost as "worth it"... while others will feel it is "not worth it".

Similar concerns emerge related to credential technology, particularly expensive device bound credentials:

- [Likely Legal, ‘Vaccine Passports’ Emerge as the Next Coronavirus Divide](https://www.nytimes.com/2021/04/06/us/politics/vaccine-passports-coronavirus.html)

What are the social implications of these technologies?

Should the next version of https://www.w3.org/TR/vc-data-model/ preemptively add a section on digital exclusion and device bound credentials, an in particular the risks associated with non uniform adoption various groups of interest (education level, income, racial demographics, gender identity, etc).

**Comment by bumblefudge** [comment]
I think device-bound and biometric-bound identity technologies are dangerous and regulators are struggling to resist them for lack of alternatives.  Building alternatives that are "tenable" or sustainable from an economic point of view is very urgent to many human rights agendas-- it's hard to measure any of these dimensions in isolation, so a big +1 to incorporating ethical and social dimensions cross-cutting any environmental considerations.  https://twitter.com/ReclaimYourFace/status/1442764514743623686

**Comment by OR13** [comment]
Related new issue: https://github.com/w3ctag/design-principles/issues/339

**Comment by OR13** [comment]
@mprorock perhaps we can sort out some concrete proposal here. 

We have: 

- "Privacy Considerations"
- "Security Considerations"

We seem to need:

- "Ethical, Social and Environmental Considerations"

Perhaps with a pre configured paragraph in respec... Similar to this section: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations

"The ethical, social and environmental principles in [W3C Ethical Web Principles] also apply to this specification."

"Implementers of this specification are encouraged to consider how adopting this technology aligns with or deviates from the [W3C Ethical Web Principles], deviation or risks should be explicitly identified and addressed."

**Comment by rhiaro** [comment]
The Design Principles doc was recently updated and now [includes references to the EWP](https://github.com/w3ctag/design-principles/pull/327) as well as linking to EWP in the abstract and intro to section 1. Does that help? The distinction between the two documents is supposed to be that EWP is a high level, more abstract set of principles while the DP are more concrete/specific/implementable things.

> "Ethical, Social and Environmental Considerations"

+1 I'd love to see this! (In the past I've framed it, tongue-in-cheek, as a 'Dystopia Avoidance Questionnaire' to go along side the Privacy & Security questionnaire.)

**Comment by mprorock** [comment]
@rhiaro that EWP section is quite helpful, the second part I think is more what I was after

> +1 I'd love to see this! (In the past I've framed it, tongue-in-cheek, as a 'Dystopia Avoidance Questionnaire' to go along side the Privacy & Security questionnaire.)

This is nail on the head - happy to help contribute and/or take a stab at a section on this if it isn't overstepping?

**Comment by torgo** [comment]
We think this issue is closed as we've linked from the design principles to the ethical principles and will continue to add such cross-links as appropriate as we continue work on both documents..
