### ISSUE TITLE
should discuss reasons to provide live vs. static objects

### ISSUE THREAD

**Issue by dbaron** [w3ctag/design-principles#34]
The design principles document should probably talk about the reasons to have live vs. static objects in API design.  (The classic example of this is <code>getElementsByTagName()</code> returning a live <code>NodeList</code> that changes over time as the document changes vs. <code>querySelectorAll()</code> returning a static <code>NodeList</code> that represents the result of the query at the time of the function call.)

Some initial thoughts:

Advantages of live objects include:
- performance when the things provided by the object are expensive to compute up front (e.g., <code>getComputedStyle</code>)
- providing a sensible API when the object only exists to "namespace" a group of related functionality (but, beyond that, is really just an extension of the object it's attached to) (at a stretch, maybe <code>window.history</code> is an example here?)
- providing a sensible API when the object needs to have setters that mutate the state that it represents (e.g., <code>window.indexedDB</code>)

Advantages of static objects include:
- performance when the things provided by the object are expensive to keep up-to-date for the lifetime of the object (e.g., <code>querySelectorAll</code>)
- matching expectations of API users who expect the result of a method not to change under them

I'm sure there's a good bit more to list here, though, and I'm not particularly confident that the points above are in sensible categories.

It's certainly then worth linking to [Attributes should behave like data properties](https://w3ctag.github.io/design-principles/#attributes-like-data) to point out that static objects that can change over time need to be the result of methods rather than attributes.

(It may also be worth discussing static vs. frozen.)

**Comment by dbaron** [comment]
Just had a brief chat with @annevk and @domenic about this.

A few thoughts from that:
 * much of the push for "everything should be static" is particularly about collections.  This guideline applies most strongly to things that have a length that can change (e.g., element.childNodes, document.getElementsByTagName()); making objects like this live is particularly poor API design since users of the API can easily fall into traps when the collection changes while being iterated, etc., and it's a case where the collection being live is most surprising.
 * there does appear to be a connection between attributes vs. properties.  Things that change frequently should probably come from methods, but it is OK for attributes to change sometimes (though it's required that they not change between two consecutive gets with nothing in between).  So attributes can return static objects (e.g., frozen Array) that occasionally change.

**Comment by dbaron** [comment]
Another disadvantage of static objects is that they generate garbage for each access.

**Comment by marcoscaceres** [comment]
> Another disadvantage of static objects is that they generate garbage for each access.

Could you be a bit more specific?

**Comment by dbaron** [comment]
That if you have a code pattern like:
```
  element.getTiming().duration
  ...
  element.getTiming().fill
```
you've created two different objects for the two different getTiming() calls.  If the object is large, this could be problematic, depending on the typical calling pattern.

**Comment by marcoscaceres** [comment]
ah right, thanks!
