### ISSUE TITLE
JS WeakRefs proposal

### ISSUE THREAD

**Issue by littledan** [w3ctag/design-principles#36]
In https://w3ctag.github.io/design-principles/#js-gc , it's mentioned that WeakRefs are not proposed for ECMAScript. However, they're actually a Stage 1 proposal championed by Dean Tribble, see [repository](https://github.com/tc39/proposal-weakrefs). It'd be nice to change the design principles document to cross-reference this, rather than an outdated reference to the dead wiki. 

Does the W3C TAG have a particular point of view on the WeakRefs proposal? This would be useful information to bring to TC39.

cc @slightlyoff @domenic @dtribble

**Comment by domenic** [comment]
I updated the document to reference the new proposal. I think it would be good to see if the TAG has feedback on this; maybe @slightlyoff can take point on ensuring that gets on the agenda at some point?
