### ISSUE TITLE
Add Privacy/permissions related guidance

### ISSUE THREAD

**Issue by travisleithead** [w3ctag/design-principles#37]
Device APIs...
* Known privacy issues affecting API or User agent design guidelines should be mentioned in the spec to increase awareness
* Make your API work well with the permission APIs
* Design for various privacy considerations (is this one-time use? repeated use? coarse-grained data, fine-grained data? -- and ensure a fine-grained permission is minted for each of these scenarios)
 
From the [mintues](https://pad.w3ctag.org/p/2016-11-02-minutes.md):
Normative spec stuff - fine-grained permissions enable clear auditing with who is using what permissions. Fine-grained permissions is what
we're going towards. So the user agent can mediate access to capabilities. The UA may want to coalesce these permissions together when
asking users about them.

**Comment by travisleithead** [comment]
Also, review this: https://gist.github.com/mnot/96440a5ca74fcf328d23 to see if there anything worth lifting into the API design guidelines...

**Comment by lknik** [comment]
I agree such a document is needed. We actually discussed similar ideas at DAS for a while now.
I'm happy to work on it from the privacy design and considerations side.

**Comment by tobie** [comment]
Are you planning to tie this into https://www.w3.org/TR/security-privacy-questionnaire/ ?

**Comment by travisleithead** [comment]
Looks like we've at least linked across to that in https://w3ctag.github.io/design-principles/#other-considerations

**Comment by torgo** [comment]
(As agreed in TAG teleconf https://github.com/w3ctag/meetings/blob/gh-pages/2017/telcons/01-11-agenda.md.)
