### ISSUE TITLE
Should charters link to the TAG design principles?

### ISSUE THREAD

**Issue by svgeesus** [w3ctag/design-principles#407]
([Originally raised in 2020](https://github.com/w3c/charter-drafts/issues/303) on the charter-drafts repo)

Specifications which go to TAG review as part of horizontal review will do better if they follow the TAG design principles. One way to help ensure that would be to add a statement like 

> This Working Group expects to follow the TAG design Principles

to the [charter template](https://w3c.github.io/charter-drafts/charter-template.html), so that new charters all have that text. Is the TAG happy to have such a statement added? I see that there has been [a /TR publication in August 2022](August 2022) so there should be no concern about the authority of such a reference. (Two years ago the dsign principles looked less official, which raised a concern for some).

Oh by the way, looking at the [3 Oct 2022 ED](https://w3ctag.github.io/design-principles/) I notice there is no changes section. While not mandatory, it does help others review documents without poring over commit logs.

**Comment by svgeesus** [comment]
Happy New Year and gentle ping

**Comment by LeaVerou** [comment]
@plinss @cynthia and I discussed this today in a breakout and we decided that yes, we would be happy to have this statement added. WG chairs can always decide to remove it. 😊

> Oh by the way, looking at the [3 Oct 2022 ED](https://w3ctag.github.io/design-principles/) I notice there is no changes section. While not mandatory, it does help others review documents without poring over commit logs.

This is a good point. In the same breakout, we explored ways to semi-automate this, and will pursue it.

**Comment by svgeesus** [comment]
Thanks, [added to the charter template](https://github.com/w3c/charter-drafts/commit/0192cfbf4ea3b5ce9960af7ece5873cfa3bd4eea).
