### ISSUE TITLE
"Make method arguments optional if possible" section has bad advice

### ISSUE THREAD

**Issue by bakkot** [w3ctag/design-principles#437]
[This section](https://w3ctag.github.io/design-principles/#optional-parameters) says

> The API must be designed so that if an argument is left out, the default value used is the same as converting [undefined](https://webidl.spec.whatwg.org/#idl-undefined) to the type of the argument. For example, if a boolean argument isn’t set, it must default to false.

and I think that's basically wrong? A string-taking API should not be required to use the default value `"undefined"`, which is what you get when converting `undefined` to a string (unless this document is using "converting" in an unusual way, i.e. not just `'' + undefined`). Similarly, `NaN` is almost never the right default for a Number-taking API, and `0` is only sometimes a reasonable default for an integer-taking API, which are what you get when converting `undefined` to a Number or [integer](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-tointegerorinfinity) in JS.

Rather, the way I'd put it is that an explicit `undefined` should be treated exactly the same as an option being absent[^1]. And, in addition, `false` should be the default for boolean parameters. This doesn't tell you anything about the appropriate default for other type, though.

(That rule appears to have been introducing in https://github.com/w3ctag/design-principles/pull/228.)

[^1]: except in the (very rare) cases where `undefined` is a coherent value to use - for example, in JS the `cause` parameter in error constructors can take any JS value, including `undefined`, so that's one of the very rare cases which breaks this rule.

**Comment by bathos** [comment]
> [...] which are what you get when converting undefined to a Number or [integer](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-tointegerorinfinity) in JS.

I’d have imagined “converting” here referred to [ES → Web IDL conversion](https://webidl.spec.whatwg.org/#dfn-convert-ecmascript-to-idl-value), likewise [type of the argument](https://webidl.spec.whatwg.org/#idl-types) and [boolean](https://webidl.spec.whatwg.org/#idl-boolean) in their Web IDL senses. If that’s accurate, then it doesn’t follow that converting undefined to the type of the argument always aligns with outcomes like “"undefined"” and `NaN`.

(I agree with the conclusion about this passage regardless, but figured it was worth pointing out that this reads pretty differently if `type` means Web IDL type and not ES language type. As for whether that was the intention, I’m not certain.)

**Comment by bakkot** [comment]
Ah, that's probably correct. Looks like it works out the same in practice - [converting `undefined` to a DOMString](https://webidl.spec.whatwg.org/#es-DOMString) does still give you `"undefined"`, e.g..

**Comment by bathos** [comment]
Yep, but if the type were `DOMString?`, the “correct” default would be `= null`. The original text makes a bit more sense to me with that reading, but it’s confusing and your suggested replacement gets the key point across better.
