### ISSUE TITLE
Recommend [Constructor] for creation vs. createXXX() methods

### ISSUE THREAD

**Issue by travisleithead** [w3ctag/design-principles#44]

**Comment by domenic** [comment]
I think this should also *recommend* createXXX() methods for async creation instances where it's impossible to synchronously construct something; see https://github.com/whatwg/html/issues/2340

**Comment by slightlyoff** [comment]
So we discussed this at today's F2F in London, and roughly, `createImageBitmap` does a few things. It:

 - `new`s up an `ImageBitmap` instance which is uninitialized
 - takes some data and initializes the instance
 - does "stuff" with the data (perhaps asynchronously)
 - returns the promise that represents the previous step

All of this can (and should!) live in public API space on the class, in this case `ImageBitmap`. This mean that `createXXX()` methods are fine as syntactic sugar over the above, but do not absolve designers of the need to expose and epxlain that logic. In the case of `ImageBitmap` we could write this at:

```js
class ImageBitmap {
  constructor(image = null) {
    // private-ish, if we get real private can be easily explained
    this._imageData = null;
    this._initialized = false;
  }

  initFromImage(imageSource) {
    if(this._initialized) {
      // error or thow 
    } 

    // do stuff here
    return new Promise((res, rej) => {
      // async results here
      this._imageData = stuff;
      this._initialized = true;
      res(stuff);
    }); 
  }

  get data() {
    if (!this._initialized) {
      // error or throw? Dunno
    }
    return this._imageData;    
  }

  crop(sx, sy, sw, sh) {
    if (!this._initialized) {
      // error or throw?
    }
    // crop and return async
    return new Promise((res, rej) => {
      this._imageData = <result of cropping>;
      res(this._imageData);
    });
  }
}

WindowOrWorkerGlobalScope.createImageBitmap = function(image, ...options) {
  let ib = new ImageBitmap();
  return ib.initFromImage(image).then(() => {
    let processingOptions = null;
    let cropOptions = null;
    if (options.length > 1) {
      // treat them as crop arguments
      let cropOptions = options.slice(0, 3);
      if (options.length > 4) {
        processingOptions = options[4];
      }
    } else {
      if (options) {
       processingOptions = options[0];
      }
    }
    if (cropOptions) {
     return ib.crop(...cropOptions).then(() => { return  ib.process(processingOptions); });
    } else {
      return ib.process(processingOptions);
    }
  });
};
```

**Comment by domenic** [comment]
I am torn. I like not having magic. But I am not sure whether it is a good idea to allow you to create (via the constructor) instances of a class with invalid internal states. That means all APIs must now include a check "is the internal state valid?" before using them.

Another issue is that I believe ImageBitmap is meant to be an opaque handle with the actual data held in GPU memory, so we do not want to provide a synchronous `data` getter.

Finally, this all becomes less "magical" if you realize it can be modeled like so:

```js
const theSecret = {}; // opaque object known only to the browser

class ImageBitmap {
  constructor(secret = undefined, handle = undefined) {
    // `= undefined` above to preserve length 0 required by IDL
    if (secret !== theSecret) {
      throw new TypeError("Illegal constructor");
    }
    
    this._imageDataHandleOnGPU = handle;
  }
  
  // ...
}

self.createImageBitmap = function (image, ...options) {
  return sendToGraphicsCardAndProcessOnTheGraphicsCard(image, options).then(handle => {
    return new ImageBitmap(theSecret, handle);
  };
};
```

That is, it is perfectly possible to design the API so that only `createImageBitmap` has the ability to call the constructor. It's not really magic, just encapsulation, similar to other languages where you might mark the constructor `internal` to your package.

**Comment by plinss** [comment]
Note that WebIDL has constructors now: https://heycam.github.io/webidl/#idl-constructors

**Comment by cynthia** [comment]
I suspect this belongs somewhere in or near this: https://w3ctag.github.io/design-principles/#constructors
