### ISSUE TITLE
"while a JavaScript event loop is running." is probably not intended

### ISSUE THREAD

**Issue by jakearchibald** [w3ctag/design-principles#456]
https://w3ctag.github.io/design-principles/#js-rtc

> Don’t modify data accessed via JavaScript APIs while a JavaScript [event loop](https://html.spec.whatwg.org/multipage/webappapis.html#event-loop) is running.

An event loop is running from the creation of an agent, and it doesn't stop until the agent is destroyed. By this definition, data can never really update.

This should probably be reworded in terms of [running scripts](https://html.spec.whatwg.org/multipage/webappapis.html#calling-scripts) and [callback invoking](https://webidl.spec.whatwg.org/#invoke-a-callback-function).

It might be worth calling out that `new Date()`, `Date.now()`, `performance.now()` are accepted breakages of this rule.

In fact, it's interesting to compare `performance.now()` to `document.timeline.currentTime`, as the former breaks run-to-completion, whereas the latter is stable for the whole frame (beyond a single callback).

**Comment by torgo** [comment]
Hi Jake - thanks for sending us this! We discussed today and absolutely agree this needs to be fixed. Would it be possible for you to suggest a more concrete re-wording that we could consider?

**Comment by annevk** [comment]
You probably want to say that in general you shouldn't manipulate data while JavaScript is running (e.g., as the result of an event, callback, etc.).

**Comment by jakearchibald** [comment]
Data can update synchronously from the result of developer action. Eg, `node.remove()` changes the DOM synchronously and is immediately observable.

However, things that are not the result of developer action, or are asynchronously delivered, should not happen in the middle of other JavaScript.

Meaning, during a `while (true)`, you *shouldn't* expect things like:

- The DOM to update as a result of the HTML parser loading network content
- `img.width` to change as a result of loading image data from the network
- Buttons of a gamepad to change state
- `scrollTop` to change, even if scrolling can visually occur

These things aren't updated by the currently running script, so they shouldn't change during the currently running script. Instead, a task should be queued, or they should update as part of the render steps.

There are deliberate violations of this rule, such as `Date.now()` and `performance.now()`, which can observe changes in time, and things like the proposed [`isInputPending()`](https://wicg.github.io/is-input-pending/#dom-scheduling-isinputpending), which read from task queues.
