### ISSUE TITLE
Editorial: autolink to all cited interfaces/etc.

### ISSUE THREAD

**Issue by domenic** [w3ctag/design-principles#48]
This spec was written before I knew much about Bikeshed, so there are many cases where I used `<code>InterfaceName</code>` when I should have used `{{InterfaceName}}`. A quick pass reveals:

- https://w3ctag.github.io/design-principles/#casing-rules examples column and notes
  - Ideally these should not generate normative references; I think there's a way to do that by marking up their containers as non-normative.
- https://w3ctag.github.io/design-principles/#numeric-types I _think_ you can link to IDL types now, and you can certainly link to extended attributes.
- https://w3ctag.github.io/design-principles/#milliseconds setTimeout; linking Date would require an anchors block since ES is special
- https://w3ctag.github.io/design-principles/#times-and-dates Date again

**Comment by torgo** [comment]
Agreed at f2f: Travis will action this.
