### ISSUE TITLE
Newlines in source cause broken links

### ISSUE THREAD

**Issue by edent** [w3ctag/design-principles#491]
As seen on [the current published site](https://www.w3.org/TR/design-principles/#devices-platforms):

![image](https://github.com/w3ctag/design-principles/assets/837136/c8521d7b-be4e-4981-90b9-8afd4e6c7ac6)

This appears to be caused by a linebreak in the source document:

https://github.com/w3ctag/design-principles/blob/d893e1c5da763dca6a694d292d6ee7dd1320cb77/index.bs#L275-L277

**Comment by torgo** [comment]
Closing as we think this was fixed in https://github.com/w3ctag/design-principles/pull/492. Thanks @edent!
