### ISSUE TITLE
New principle: don't break core part of the web platform in order to enable embellishments

### ISSUE THREAD

**Issue by torgo** [w3ctag/design-principles#493]
Maybe this is fits under "leave the web better than you found it"? It came up in discussions of renderblocking / viewtransitions. Discussed on today's plenary call...

**Comment by LeaVerou** [comment]
I think we need concrete examples for a principle.

**Comment by hober** [comment]
@torgo, @rhiaro, and I talked about this during a breakout today. @torgo will write a <abbr title="pull request">PR</abbr> to add some text to the "Leave the web better than you found it" principle for this.
