### ISSUE TITLE
Assistive technology emphasis adjustments

### ISSUE THREAD

**Issue by nigelmegitt** [w3ctag/design-principles#498]
This issue is not really a specific actionable request right now, more a call for discussion in the hope of some editing improvements that would address the concerns I list below.

___

The emphasis in [§2.9 Don't reveal that assistive technologies are being used](https://w3ctag.github.io/design-principles/#do-not-expose-use-of-assistive-tech) reads to me as (I understand this is not exactly what the words say, I'm talking about the impression/steer that the words provide):

* All assistive technology usage constitutes sensitive information
* Therefore don't reveal any information about any such usage

I would like us to add some nuance to this that would be helpful-and-not-harmful to users of the web. The problems I see with the current wording and tone are:

1. There is some usage of assistive technology that is so widespread that it does not constitute sensitive information, and nobody could sensibly infer from its usage any sense that the user is more vulnerable. In particular, subtitles and captions are used by significantly more people to overcome situational barriers to access (in a noisy place, sound turned down low deliberately etc) than to overcome inherent personal barriers (deafness, hearing loss etc). However they fall under the blanket term "assistive technology".
2. Related point: assistive technology is actually not very well defined and can be situational: I don't think of my device reading messages out while I'm walking along using earbuds as "assistive technology" but it's very hard to distinguish from screen reader text to speech applications, from a definition perspective. Maybe the same constraints should apply anyway; there's a big grey area there.
3. A strict reading of the current wording would be "it's okay to ask for user consent to share information, but don't do it otherwise", but to my eyes anyway, the permission to readers to ask for consent seems buried.

The wider issue I have here is that, while I agree that it must be safe to visit web pages, the people who make web pages typically like to be able to adjust them over time to make improvements, and it is commonplace to use data, including experimentation, to decide on which changes are improvements. By preventing access to data about usage of assistive technology, the principle constitutes a judgement that exposure of information is more important than product improvement. However this in itself is a form of discrimination against users of assistive technology, since it cuts off those users from generating data for product improvements. My fear is that the effect over time is stagnation of accessibility features and a limiting of developer effort down to "whatever ticks the legal boxes we are required to tick".

Can we find some wording changes to provide additional encouragement to seek limited consent to share information, and to continually improve web pages and web-based products in general so that they work well for everyone, while continuing to safeguard vulnerable users?

**Comment by hadleybeeman** [comment]
Hi Nigel! This comment has prompted a good discussion at our W3C TAG face-to-face in Edinburgh. 
  
The primary focus of the Design Principles is API and user agent development (though some of these principles are applicable to web content development).

UAs and assistive technologies themselves are able to collect usage data, to learn about their users, as are web sites. 

However, we do not want web content using an arbitrary API to be able to detect that an assistive technology at the user agent level is being used, as a byproduct of using that API. (In some cases this is unavoidable, but we aim to keep these to a minimum).

As you've pointed out, the nature of what constitutes assistive technology is context-dependent. We note this in the text, but do not explicitly define "assistive technology" for that reason.

We hope this clarifies what we are trying to accomplish, and we'd like to close the issue.

**Comment by nigelmegitt** [comment]
Hi Hadley, thanks to you and TAG for discussing this.

> UAs and assistive technologies themselves are able to collect usage data, to learn about their users, as are web sites.

This is the point though: web sites are _not_ able to collect usage data that would allow them to be improved, where that usage data concerns assistive technology, so in preventing that, the principles indirectly discriminate against those people they are intended to protect.

> We hope this clarifies what we are trying to accomplish, and we'd like to close the issue.

Sorry, it doesn't, of course you can (and have) closed the issue, but the concerns I raised remain. I don't agree that you can separate API and UA development from the products (web sites) that depend on those APIs and UAs. The APIs and UAs fundamentally constrain the web sites, and the web sites are actually what we are here for.
