### ISSUE TITLE
Make it easy to synthesize objects typically created by the UA?

### ISSUE THREAD

**Issue by RByers** [w3ctag/design-principles#51]
Often the 99% use case for an API involves the UA generating objects of a particular type (eg. `MouseEvent`).  IMHO it's important to also support the 1% case where subject objects are created by script and are (mostly) indistinguishable from the UA-generated ones.

For example, a library/component designed just for `MouseEvent` could be driven via another component that consumes `TouchEvent`s by synthesizing fake `MouseEvent` instances.  Also this is often necessary to enable good unit testing of components.

Should the design principles say something about this?

**Comment by RByers** [comment]
Here's an example where @domenic [says](https://github.com/WICG/IntersectionObserver/issues/33#issuecomment-146248475):

> Having objects be constructed magically by the platform should be reserved for truly special cases. One example use case is mocking libraries.

**Comment by domenic** [comment]
I can take this. I have been dispensing opinions around constructors for a long time, and having it written down somewhere would be great. It's a bit subtle sometimes---see e.g. https://github.com/w3c/wot-scripting-api/issues/3 where I came to the conclusion that there was too much UA magic for constructors to make sense---so this will be an interesting entry to write.

**Comment by RByers** [comment]
Great, looking forward to gleaning your wisdom!

**Comment by torgo** [comment]
@domenic you assigned yourself on this. Are you planning to submit a PR?

**Comment by domenic** [comment]
Somehow this fell off my to-do list. Let me bump it back up.

**Comment by dbaron** [comment]
Should this be merged with #44?

**Comment by dbaron** [comment]
Oh, except there's a PR for this in #80. :-)
