### ISSUE TITLE
New principle: balancing privacy and other concerns

### ISSUE THREAD

**Issue by martinthomson** [w3ctag/design-principles#511]
This was brought up in our discussion of [font exposure for people who use minority languages](https://www.w3.org/2024/09/font-i18n-privacy.html).

A proposal here is that the browser adopt the most private stance by default, but still provide a means of negotiating or selecting an option that is more respectful of other needs, like a desire to access content in a more preferred language.

**Comment by annevk** [comment]
How does that specific suggestion relate to feature design? More prompts?

(Naively, one would expect the right answer here to be to ensure that Unicode has coverage for all the world's languages and that browsers bundle fonts supporting all relevant grapheme clusters.)

**Comment by martinthomson** [comment]
@svgeesus, I know that we talked about this.  The TAG now has consensus on the topic.
