### ISSUE TITLE
Recommend for/against "is" prefix for boolean APIs?

### ISSUE THREAD

**Issue by domenic** [w3ctag/design-principles#53]
It seems like the overall platform convention is to not do that:

- event.bubbles/cancelable/defaultPrevented/composed
- { once, passive } EventListenerOptions
- response.bodyUsed/ok/redirected
- request.bodyUsed/keepalive
- htmlElement.translate/hidden/draggable/spellcheck
- htmlMediaElement.seeking/paused/ended/autoplay/loop/controls/muted
- htmlFormElement.checkValidity()/reportValidity()
- window.confirm()

However the ES spec seems to use the "is" prefix everywhere; I started listing examples but the list got too long. I think they are all methods though, not properties or options...

We also have the following platform counterexamples:

- event.isTrusted (I think this is just a historical mistake)
- canvasContext.isPointInPath()/isPointInStroke()

On balance I think the recommendation is to use the "is" prefix for methods, especially methods that are asking a question about their argument, but not for properties or options (dictionary members). And to only use it for when the method has no side effects, i.e. we should not change htmlFormElement.checkValidity() to htmlFormElement.isValid() because that loses the implication that it will actually perform a validity check (firing "invalid" events and such).

**Comment by torgo** [comment]
@dbaron : seems reasonable.

**Comment by torgo** [comment]
@cynthia to write some text based on this input.
