### ISSUE TITLE
Guidance on wrapper specs

### ISSUE THREAD

**Issue by cynthia** [w3ctag/design-principles#67]
There have been quite a few wrapper specs that have hit our review queue recently - it would be extremely useful to add bits from past reviews that apply to all wrapper specs. (I don't have a concrete list, working on that)

**Comment by torgo** [comment]
Sangwhan to write something.

**Comment by travisleithead** [comment]
e.g., Remote playback, barcode detection...

**Comment by cynthia** [comment]
This has landed in master, so should be safe to close.
