### ISSUE TITLE
Improve guidance for using attributes vs methods

### ISSUE THREAD

**Issue by plinss** [w3ctag/design-principles#70]

**Comment by dbaron** [comment]
Do we remember what this was about?  Is it related to https://github.com/w3ctag/design-principles/issues/46#issuecomment-318063402 ?

**Comment by plinss** [comment]
IIRC this was referencing the issue of having:
```
interface Foo {
    attribute thing bar;
};
```
vs:
```
interface Foo {
    thing getBar();
};
```

Interfaces are inconsistent here and it would be useful to have advice on when to use one vs the other (and a preference for when it doesn't matter for consistency). Issue #46 may be related and help guide the direction.

**Comment by kenchris** [comment]
In the Qt framework, we attempted to use something like attributes for things that were mostly getters, ie not side effects, or had to perform work. So a getBar() method could have side effects, like doing some set up and cache a value, but .bar couldn't. For methods actually doing work, like conversion we would prefix it with to* like toBar(), ie a toHTML()

**Comment by domenic** [comment]
A developer asked me about this question for their API today and I was somewhat surprised that we had not documented it. At least there is an open issue :).

I'll note that, similar to what @kenchris says, this is a well-trodden path in other languages and frameworks. Although we want to be sure that any advice in the TAG design principles conforms to existing web APIs and thus helps enforce consistency, in my experience the web hasn't done anything particularly different from other platforms so far. So, we can likely draw inspiration from existing guidelines.

Here are two guidelines from .NET that I found kind of helpful: [1](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms229054(v=vs.100)?redirectedfrom=MSDN), [2](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-1.1/bzwdh01d(v=vs.71)?redirectedfrom=MSDN#cpconpropertyusageguidelinesanchor1).

**Comment by dbaron** [comment]
> Here are two guidelines from .NET that I found kind of helpful: [1](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms229054(v=vs.100)?redirectedfrom=MSDN), [2](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-1.1/bzwdh01d(v=vs.71)?redirectedfrom=MSDN#cpconpropertyusageguidelinesanchor1).

The first of these has a list that's rather similar to what's already in [§5.1. Attributes should behave like data properties](https://w3ctag.github.io/design-principles/#attributes-like-data).  It's possible that the way we should start here is retitle that section and make it more explicitly about "how to choose between attributes and methods".

**Comment by cynthia** [comment]
This is supposed to come after the first two paragraphs in 5.1 - working on re-working the first two paragraphs.

----

Sometimes it is unclear whether to use a attribute over a method, or vice-versa:

* Attribute getters must not have any (observable) side effects.
  If you have expected side effects, use a method.
* Attribute getters should not perform any expensive operations.
  If a getter requires performing an expensive operation, it should be a method.
  (A notable failure of the platform in this regard is getters like <code highlight="js">offsetTop</code> performing layout; do not repeat this mistake.)
* Attribute getters should return the same object each time it is called.
  This means <code highlight="js">obj.attribute === obj.attribute</code> must always hold.
  Returning a new value from the getter each time is not allowed.
  If this does not hold, the getter should be implemented as a method.

Regardless of using an attribute or method, whenever possible, preserve values given to the setter for return from the getter. That is,
given <code highlight="js">obj.attribute = x</code>, a subsequent <code highlight="js">obj.attribute === x</code> should be true. (This will not always be the case, e.g. if a normalization or type conversion step is necessary, but should be held as a goal for normal code paths.)

**Comment by annevk** [comment]
`obj.attribute === obj.attribute` must hold, but it's okay for `obj.attribute` to return something different if `obj` got modified somehow (by the same thread) since the first time it was invoked. E.g., `node.firstChild` is not constant and we wouldn't want it to be and we wouldn't want it to be a method either.

**Comment by cynthia** [comment]
Thanks for the feedback. I've updated the text in the original comment. (The reason for this unconventional process is because there is a huge backlog of PRs, so conflicts are a bit of a problem.)

**Comment by cynthia** [comment]
Sometimes it is unclear whether to use an attribute or a method.

 - Attribute getters must not have any (observable) side effects.
If you have expected side effects, use a method.
- Attribute getters should not perform any expensive operations.
If a getter requires performing an expensive operation, it should be a method.
(A notable failure of the platform in this regard is getters like offsetTop performing layout; do not repeat this mistake.)
- If the underlying object has not changed, attribute getters should return the same object each time it is called.
This means obj.attribute === obj.attribute must always hold.
Returning a new value from an attribute getter each time is not allowed.
If this does not hold, the getter should be a method.

For attributes, whenever possible, preserve values given to the setter for return from the getter. That is,
given obj.attribute = x, a subsequent obj.attribute === x should be true. (This will not always be the case, e.g., if a normalization or type conversion step is necessary, but should be held as a goal for normal code paths.)

The object you want to return may be live or static. (add link to 5.2) This means:

 - If live, then return the same object each time, until a state change requires a different object to be returned.
 This can be returned from either an attribute or a method.
 - If static, then return a new object each time.
 In which case, this should be be a method.

---

Incorporates what we wanted to do in #46.

**Comment by domenic** [comment]
> If live, then return the same object each time, until a state change requires a different object to be returned. This can be returned from either an attribute or a method.

An attribute makes more sense here than a method. And, state changes that require a new object should be quite rare; live objects are, after all, live, so that they can update themselves in reaction to state changes. A new object would only make sense if you have some sort of stratification into "changed, but not enough to have a new identity" vs. "changed so much that it requires an entirely new identity".

> If static, then return a new object each time. In which case, this should be be a method.

This doesn't seem right. You can use an attribute, and return the same object, until a state change causes you to need to return a new object.

**Comment by dbaron** [comment]
> And, state changes that require a new object should be quite rare; live objects are, after all, live, so that they can update themselves in reaction to state changes.

Some common examples of state changes that led to a new object:

```js

element.removeChild(element.firstChild); // changes the object returned by element.firstChild getter

xhr.send(); // asynchronously causes the object returned by xhr.responseXML to become non-null

for (let d of document.getElementsByTagName("div")) {
  // ev.currentTarget changes as the event propagates from descendants to ancestors
  d.addEventListener("click", (ev) => console.log(ev.currentTarget));
}

**Comment by domenic** [comment]
I guess the issue here is that I've never heard the term "live object" applied to those cases. I've only heard it in the case of collections.
