### ISSUE TITLE
Give guidance on algorithms

### ISSUE THREAD

**Issue by annevk** [w3ctag/design-principles#72]
See https://github.com/w3c/requestidlecallback/issues/61 for an example.

I'm not entirely sure how to phrase this, but we basically want algorithms in specifications to reflect best practices in programming. So no stack introspection, side-effect-free if possible, etc.

**Comment by annevk** [comment]
Relates a bit to #10 I suppose.

**Comment by torgo** [comment]
Closed as a duplicate of #10.
