### ISSUE TITLE
Call this design guidelines?

### ISSUE THREAD

**Issue by annevk** [w3ctag/design-principles#74]
It's not really principles. Our principles are https://www.w3.org/TR/html-design-principles/ (just ignore the unfortunate HTML prefix).

**Comment by torgo** [comment]
We could reference the html design principles from our doc or we could pull in the principles from the referenced doc. Some discussion on this needed.

**Comment by kenchris** [comment]
I am totally OK with renaming this. These are definitely guidelines.

I don't know how to handle renaming the repo though

**Comment by hober** [comment]
> We could reference the html design principles from our doc or we could pull in the principles from the referenced doc. Some discussion on this needed.

Maybe we can forward-dup this to #160?

**Comment by annevk** [comment]
Sure.
