### ISSUE TITLE
Sequences vs arrays

### ISSUE THREAD

**Issue by dbaron** [w3ctag/design-principles#76]
Copying this issue from https://github.com/w3ctag/api-design-guide/issues/1 raised by @marcoscaceres 

<blockquote>
It would be great if the document could provide guidance on when to use a sequence vs when to use an array in an API.

See:
sysapps/telephony#81
</blockquote>

There's also a brief conversation there.

**Comment by domenic** [comment]
Sequence is just the Web IDL name for arrays. Maybe the action item here is to make that clearer in the Web IDL spec?

**Comment by travisleithead** [comment]
Yes, this is correct. I'm wondering if this had to do with the (now defunct) Type[] in WebIDL. I don't think we need any particular guidance on sequences vs. array.

**Comment by travisleithead** [comment]
We agreed to close.
