### ISSUE TITLE
Add principles for registries

### ISSUE THREAD

**Issue by triblondon** [w3ctag/design-principles#83]
We have been asked by the AB (on TAG member ML) to look at establishing best practice for registries:

> The AB also encourages the TAG to write a "design patterns for registries" document to aid Working Groups who may be considering a new registry to accompany their specification(s).  The TAG could also provide guidance on which registries, tables, or other material currently embedded within a Recommendation should be candidates for extraction (as an Amended Recommendation) and made into registries.

/cc @jeffjaffe

**Comment by torgo** [comment]
Closing and folding this into #68.
