### ISSUE TITLE
Add advice on polyfills

### ISSUE THREAD

**Issue by triblondon** [w3ctag/design-principles#84]
At TPAC, most people who came to the polyfills breakout had not heard of the polyfill finding, including most polyfill authors.  We should do a better job of marketing on a number of fronts, and one of those would be to include a polyfill point in design principles.  This could point to the finding, but should also include some very high level guidance and perhaps distinguish between script related features and elements, (see https://github.com/w3ctag/polyfills/issues/31)

**Comment by torgo** [comment]
@triblondon to copy the key design principles points from polyfill finding (and linking to the finding) and submit as a PR.
