### ISSUE TITLE
Guidelines for binary stream-likes should be added

### ISSUE THREAD

**Issue by travisleithead** [w3ctag/design-principles#86]
Moving https://github.com/w3ctag/design-reviews/issues/92 into this repo. This will be the primary entry point for the goals stated in the previous issue:

* Get the various streams straightened out
* Understand the use cases
* Write it all down (or at least the good parts) into our Design guidelines.

Relevant Meeting minutes: 
* https://pad.w3ctag.org/p/30-10-2015-minutes.md
* https://pad.w3ctag.org/p/2016-07-30

We want to provide developers with a guide to when/how to use Streams (and what kind) in their designs.

* For binary-streams (unlike other Streams like MediaStream) issue https://github.com/w3ctag/design-principles/issues/56 is tracking. (Though, maybe we can close that one?)

**Comment by dbaron** [comment]
Is this a duplicate of #56?

**Comment by travisleithead** [comment]
Closing as duplicate.
