### ISSUE TITLE
Guideance should discourage the use of the bitmask pattern (compareDocumentPosition)

### ISSUE THREAD

**Issue by travisleithead** [w3ctag/design-principles#87]
Looks like this is coming up again in WebGPU effort.
https://github.com/gpuweb/gpuweb/blob/master/design/sketch.webidl

See `WebGPUBufferUsageFlags` in that proposal.

I think the reasons against a bitmask for a webapi are: ergonomically tricky to reason about; dictionaries are more logically suited for a set of configuration flags... more?

**Comment by annevk** [comment]
We stopped using non-string constants a long time ago to identify things?

**Comment by travisleithead** [comment]
Yep, but for folks in the wasm space, numbers are faster than strings, so this comes up again...

**Comment by annevk** [comment]
Wasm could have a different binding for enums, no?

**Comment by travisleithead** [comment]
I suppose so, but I'm not sure how that relates to the bit-mask pattern in question here? Please elaborate.

**Comment by rektide** [comment]
What would a design-principles respecting WebGPUBufferUsage look like?

```
dictionary WebGPUBufferUsage {
    bool MAP_READ;
    bool MAP_WRITE;
    bool TRANSFER_SRC;
    bool TRANSFER_DST;
    bool INDEX;
    bool VERTEX;
    bool UNIFORM;
    bool STORAGE;
}
```

Right? I'd like to make sure I understand what cfa5526f80197ec495c4e9055cb39f3809f0438a is telling me.

**Comment by cynthia** [comment]
Yes, that is the intent of the text in the document. If this turns out to be a common pattern which needs to be optimized that can probably be standardized to some extent.

**Comment by annevk** [comment]
@rektide without the uppercase member names. There's naming guidelines for dictionaries that would need to be respected.
