### ISSUE TITLE
Add justifications

### ISSUE THREAD

**Issue by ethanresnick** [w3ctag/design-principles#9]
The document says it will explain the rationale behind each principle, but currently does very little of this. Take the first couple principles on having strong primitives: what makes this so important? The document doesn't yet say.

**Comment by torgo** [comment]
Is this still relevant? In fact the document doesn't currently state it will explain the rationalie so this may have been overtaken. However, the document may need to take a stronger view here and explain some of the basic overriding principles in an intro section before delving int it. It also needs an abstract.

**Comment by torgo** [comment]
@travisleithead to write some intro text that will enumerate some of the basic principles.

**Comment by torgo** [comment]
We're going to close this off take it as feedback applicable across the document.
