### ISSUE TITLE
Add notes to consider private browsing ("incognito") mode

### ISSUE THREAD

**Issue by cynthia** [w3ctag/design-principles#97]
There are specifications that should most likely behave differently (or be completely disabled) in private browsing mode - a guideline on this should be included in our guidelines.

**Comment by hober** [comment]
We should probably reference [The Web should be accessible in private and normal browsing modes](https://www.w3.org/2001/tag/doc/private-browsing-modes-20190705#accessible-private-normal) from the design principles document, at least the bit that we should design features that do not expose to script whether or not the user is in private browsing mode.
