### ISSUE TITLE
Will TAG suggest async/wait for asynchronous APIs ?

### ISSUE THREAD

**Issue by igarashi50** [w3ctag/design-principles#98]
The Client-Side Design Principle  suggests to use Promise for asynchronous APIs, but ECMA Script 2017 now supports async/wait as an alternative to Promise. If async/wait is better than Promise, will the Client-Side Design Principle be updated?  In the case, what is the implication on the existing API standards based on Promise?

**Comment by annevk** [comment]
I think there's a misunderstanding. Async/await makes promises easier to use. You still need APIs to return promises. https://en.wikipedia.org/wiki/Syntactic_sugar might help.

**Comment by sigwisteria** [comment]
Is there a case that async/await is easier to understand in code examples in the API document?  I do not have knowledge whether it affects API design.

**Comment by marcoscaceres** [comment]
It definitely makes it easier to understand/write code examples, so at least in examples it should be encouraged (depending on situation)... however, it has no impact on API design.

**Comment by annevk** [comment]
Nobody who replied thus far is on the TAG, but you should feel free to use async/await in examples. They can make things a lot easier to read.

**Comment by igarashi50** [comment]
We would appreciate if TAG would update [Promises-guideline](https://www.w3.org/2001/tag/doc/promises-guide) to include the aspect of  async/wait, i.e. syntax-sugar, and examples for spec writers.

**Comment by marcoscaceres** [comment]
That wouldn’t make a lot of sense in the guide, because it deals with how to use promises within spec algorithms (where new promises either rejected or resolved can be returned based on some internal state). It doesn’t deal with higher level examples. 

However, as Anne said, you are free to use async/await in your own specs in examples. Take a look at Payment Request API spec for instance. It has good examples of how async/await can be used to illustrate API usage.

**Comment by marcoscaceres** [comment]
@igarashi50, some excellent guides for you is:

https://developers.google.com/web/fundamentals/primers/promises
https://developers.google.com/web/fundamentals/primers/async-functions

I'd suggest this be closed.

**Comment by kenchris** [comment]
You design async APIs following our advice on using promises and that would make it work with async/await
